### ISSUE TITLE
Etudes only work on caster

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#1021]
Not seeing a buff icon on party members either, only the caster.

Revision 6263669
Server Classic

**Comment by teschnei** [comment]
did you cast it on them..?

**Comment by Scavenge** [comment]
could it also possibly be the sql setting for target? i believe there's ones like 'target ally', 'target aoe allies', 'target enemy', 'target aoe enemy', i remember earlier in Sea the aerns were putting random buffs on players and using tp moves on themselves until we adjusted that.

**Comment by Scavenge** [comment]
could it also possibly be the sql setting for target? i believe there's ones like 'target ally', 'target aoe allies', 'target enemy', 'target aoe enemy', i remember earlier in Sea the aerns were putting random buffs on players and using tp moves on themselves until we adjusted that.  

edit: just checked spell_list.sql and for the etudes, the 'validTarget' column is set to 3 rather than 129, which is what the other bard songs are that do aoe to allies, like army's paeon.  but there is also an aoe column which is set to 0, and it seems all the other songs are set to 5.  

spell_list.sql beginning at line 479


update spell_list set validTargets = 129 where ((spellid > 423) and (spellid < 438);
update spell_list set AOE = 5 where ((spellid > 423) and (spellid < 438);

would work as far as i can tell but i have not tested it

**Comment by teschnei** [comment]
Etudes are a single target spell. You are supposed to target the ally you
want to put it on.

**Comment by personaone** [comment]
I'll try to reproduce this buy today but I don't think it's genuine.

**Comment by whasf** [comment]
Etudes are single target.
http://wiki.ffxiclopedia.org/wiki/Etude

**Comment by xipies** [comment]
Sorry, I misunderstood etudes. There's still an issue which I've added here: https://github.com/DarkstarProject/darkstar/issues/1048
