### ISSUE TITLE
Adding CMake support + compilation on FreeBSD

### ISSUE THREAD

**Issue by Bapabooiee** [DarkstarProject/darkstar#1037]
GNU Autotools is a horror show for the build process on FreeBSD, and I couldn't really get it to work, so I've been working on converting to CMake instead. It's still a work-in-progress, but building now works fine for FreeBSD, Linux and Windows on my CMake'd branch.

So I'm wondering if there'd be any interest in eventually merging-in a few CMake files, because in addition to getting builds working on FreeBSD:

* Linux would no longer require GNU Autotools for the build process, and it could be eliminated.
* You could run something like `mkdir build ; cd build ; cmake .. ; make` which'd keep the source tree clean of all build-related files.
* On Windows, it can dynamically generate completely-functional MSVS .vcxproj/.sln files (which is what I do, and it doesn't really change the workflow) so they wouldn't need to be tracked by source-control.
* The only additional dependency would be on cmake, and all you'd have to do is run `cmake .` and `make` on all POSIX platforms, And on Windows, you'd run `cmake . -G "Visual Studio 12 2013"` instead and then work inside MSVS as usual. This could be automated by using a .bat file or CMake-GUI.

Yeah, I know, don't fix what ain't broken, but I think it'd be worth adding CMake support simply for getting building working on FreeBSD.

My WiP cmake'd branch (which is still missing some stuff like differentiating between linking 32-bit and 64-bit import libraries for Windows) can be found here:
https://github.com/Bapabooiee/darkstar/tree/cmake

The main file for building DSP with CMake (with 3 extra files in the cmake/ dir for header/library detection) can be found here, and it currently works for building on all 3 platforms:
https://github.com/Bapabooiee/darkstar/blob/cmake/CMakeLists.txt

I've also setup buildbot and different build-slaves to automate testing compilation using cmake on Linux/FreeBSD/Windows here, if anyone fancies that:
http://buildbot.homenet.org/waterfall

Thanks, and let me know what you think.

**Comment by Cloudef** [comment]
I'm all for cmake, it's ugly but solves problems. And you in theory, only need to maintain single build system for all platforms. (In practice it will need some care).

As for the cmakelists itself, I would not use globbing, as IIRC that makes cmake unable to track changes. Instead of hardcoding CXX_FLAGS use the add_definitions. I don't think "include_directories(/usr/local/include)" is needed.

As for the includes, don't do that. Specify CMAKE_MODULE_PATH instead and use the FindFoo.cmake, to create standard find cmake script for packages. Giving paths for FIND_<FOO> commands is rarely needed, and usually complicates things. (Search paths should be set by packager, not build system, unless the files need to be searched from source).

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/pull/1036
