### ISSUE TITLE
Windurst Misson 7-2 'Awakening of the Gods' not giving Key Item from final CS.

### ISSUE THREAD

**Issue by Djcocha** [DarkstarProject/darkstar#1086]
(DSOldSchool Server)
Trading Cursed Key to the Granite Door in Temple of Ugg gives CS and everything but not 'Book of the Gods' key item to take back to Leepe-Hoppe.

**Comment by gedads** [comment]
Yes, because of 2 cs chaining you'll not receive the item.
Actually dsp makes you go through the door as a cs then you get the actual cs for the mission.
Retail displays directly the cs with the tarutaru and you receive the KI normally.
got a fix fot it but i 'm waiting my mission 9-2 to be finished before comitting it

**Comment by Djcocha** [comment]
Okay thank you (:

**Comment by Djcocha** [comment]
Hey, so I see that you went and committed that 7-2 fix early, I thank you for that.
Whasf just now updated DSOldSchool, so I went and retried and this time it just gives the 'going through door' CS and takes key away, and does nothing mission related.

I'm on client /ver 30150213_2, so I was wondering if it is an 'I need to update client.' Issue or if it has something to do with me already getting the Cutscene and it is something I need to have fixed by GM...

**Comment by whasf** [comment]
It's because he's using a new variable WINDURST72 at the door check. I changed yours to 4 and you got the cutscene and were able to progress.

I made a temporary change to the script to account for the new variable that current players won't have:
in function onTrade() at the top of the function:

if(player:getCurrentMission(WINDURST) == AWAKENING_OF_THE_GODS and player:getVar("WHASFWINDURST72FIX") == 1) then
	player:setVar("WINDURST72",4);
	player:setVar("WHASFWINDURST72FIX",0);
	end
	--
====
I gave every character a charvar (except yours of course) to make this temp fix work. Here is the SQL:

insert into char_vars (charid, varname, value) select charid, "WHASFWINDURST72FIX",1 from chars
