### ISSUE TITLE
"Additional effect" mods on weapons proc for full damage even when level sync'd

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1123]
A level 30+ warrior with a "Mammut" great axe equipped in a level 16 sync party.

Hits a mob for 5, and additional effect on the Mammut weapon procs for 20 damage consistently, when the average hit on a crab in that party is 5-6.

**Comment by TeoTwawki** [comment]
Side effect of us not having proper retail alt stats for when equipment is sync'd down, and the fact these aren't really supposed to check player lv (on retail no matter I got same dmg at multiple lv diff's)...Maybe we should lv correct it until gear sync is done retail accurate tho, because I can see that taking a long time to happen and this can be exploitable in its current state..

**Comment by TeoTwawki** [comment]
That or maybe could compare the item lv to players current (sync'd) lv to cut down the effect?

**Comment by teschnei** [comment]
additional effect weapons are supposed to not proc at all if the weapon is
under its normal level

FYI: we have proper retail alt stats for when equipment is scaled down
(except disabling add. effects apparently)

**Comment by TeoTwawki** [comment]
I completely forgot they should disable.

But as far as evereything else being 100% retail..Nuh uh. Have def seen some items not match the same stats they had synced to same lv as in retail, so whatever we're doing there isn't exact.

**Comment by teschnei** [comment]
that's a bug then, find an item and a level where it's wrong and get
reportin
