### ISSUE TITLE
Client crashes upon use of "Scroll of Monomi: Ichi"

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1254]

**Comment by b03605079** [comment]
It works with mine. "Monomi: Ichi" is restricted by expansion maybe you should check it?

**Comment by dazusu** [comment]
It's required expansion was changed on our server to rotz. This was also done with repose which works fine

**Comment by starlightknight** [comment]
@dazusu ROTZ isn't a valid value for expansion - I was going to have it be one but teschnei had me back it out since we don't otherwise support toggling ROTZ off. 

If you have it set to ROTZ that's probably your problem - just null it out if you want it to be allowed with Zilart (or if you want all spells enabled, just turn off expansion restriction in the settings)

**Comment by xdemolish** [comment]
hurray for custom issues!
