### ISSUE TITLE
Unable to HQ Steel Bullets

### ISSUE THREAD

**Issue by mrobinson9482** [DarkstarProject/darkstar#1357]
Steel bullets can be made but do not HQ.

**Comment by nesstea** [comment]
that is handled in synth_recipes table. find the entry for it by searching for the result and ingredients.

**Comment by nasomi** [comment]
This recipe is correct in the database.

**Comment by nesstea** [comment]
got a query for me? (lazy)

**Comment by nasomi** [comment]
SELECT * FROM synth_recipes WHERE synth_recipes.Result = 18723

**Comment by csundman** [comment]
I just wanted to point something out here, since I noticed behavior like this a long time ago on my server and tracked down the problem and fixed it.  (I don't know how to safely request merges to the main github... or I would have by now.)

If it's the same problem I was seeing, the issue is likely here:

https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/synthutils.cpp#L360

Notice that HQ Tier 3 occurs between difficulty difference of  -31 and -50 inclusively.  HQ Tier 4 occurs at -51 and below.  This of course... leaves out all float values between -50 and -51, which is a problem because moon phase and synth direction adjustments add and subtract float values from the difficulty of the synth.

Since Steel bullets are difficulty lvl 48 alchemy, if you have 99 in alchemy and the moon phase + day + synth direction put your difficulty difference between -50 and -51, it will be impossible to HQ.

Easy fix:  Change all HQTier test ranges to inclusive of all float values.
