### ISSUE TITLE
Non retail behavior of signet staves

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1491]
All 3 signet staff have same issues.

http://ffxiclopedia.wikia.com/wiki/Republic_Signet_Staff
- The Signet effect gained from this enchantment will overwrite Sanction and Sigil.
- The enchantment can only grant Signet to Bastokan characters.
- The enchantment can only be used in areas subject to Conquest.
- The enchantment can only be used on characters in the caster's party.
- ~~The duration of Signet gained from this item is 5 hours.~~ _fixed duration in #1536_

I currently cannot use republic staff on a party member when we are both Bastokan and standing in Labyrinth of Onzozo which is a Conquest zone, ~~the duration is incorrect,~~ and it doesn't remove sanction or sigil. I don't think any checking is even done for players nation or the zone/region type for conquest right now.

**Comment by TeoTwawki** [comment]
Oh..And the animation is wrong, and I just discovered I can target it on myself if and only if I select myself before going into the item menu.

**Comment by xdemolish** [comment]
i take it this was fixed in #1536?

**Comment by TeoTwawki** [comment]
@xdemolish No, not completely. I had edited the original post I made to reflect the part I fixed (its crossed out and referenced the pull request).

**Comment by TeoTwawki** [comment]
These should be fairly easy fixes for anyone with the time to play with it.

**Comment by helixhamin** [comment]
For this and the removal of sigil and sanction, can it be fine similar to the guards?

`target:delStatusEffect(EFFECT_SIGIL);
        target:delStatusEffect(EFFECT_SANCTION);
        target:delStatusEffect(EFFECT_SIGNET);
        target:addStatusEffect(EFFECT_SIGNET,0,0,18000);`

**Comment by TeoTwawki** [comment]
@helixhamin yup

**Comment by helixhamin** [comment]
@TeoTwawki Noted. I will see what I can do. I have been away too long and want to get back to trying to learn and contribute. And sadly, next week I will be bored out of my mind, so good time to try to help give back.

**Comment by TeoTwawki** [comment]
@helixhamin  I had forgotten all about this till github pinged me on it.

**Comment by helixhamin** [comment]
Eh, stuck waiting for my work notebook to have C formatted and the OS reinstalled, so I was just browsing the old issues.

**Comment by helixhamin** [comment]
One quick question @TeoTwawki to make sure I fix these properly, since the same problem is present in all staves.
I see this code:
(player:getNation() == (SANDORIA, BASTOK, WINDURST))

So, can I basically add that:
```
function onItemUse(target)
if (player:getNation() == SANDORIA)
   if (target:getNation() == SANDORIA)
   target:delStatusEffect(EFFECT_SIGIL);
   target:delStatusEffect(EFFECT_SANCTION);
   target:delStatusEffect(EFFECT_SIGNET);
   target:addStatusEffect(EFFECT_SIGNET,0,0,18000);
   else
   end;
else
end;
end;
```

Does this seem correct? Would like to add the nation restrictions at the same time, rather than do one pull for the status effect deletions and another pull for the nation checks.

**Comment by helixhamin** [comment]
https://github.com/DarkstarProject/darkstar/pull/2771

**Comment by metalfiiish** [comment]
Reason that code didn't work is that player isn't passed for onItemUse, as well SANDORIA was never defined. We can get away with using either, conquest, mission or quest to use their defined NATION_SANDORIA, etc.  However, due to how onItemUse was written, you won't be able to do the party check to ensure the target is in the same party as the user that is using the item.  Though something like this should fix several of the issues:   
`require("scripts/globals/conquest");
require("scripts/globals/zone");

function onItemUse(target)
    if (target:getNation() == NATION_BASTOK and target:getCurrentRegion <= 23) then
        target:delStatusEffect(EFFECT_SIGIL);
        target:delStatusEffect(EFFECT_SANCTION);
        target:delStatusEffect(EFFECT_SIGNET);
        target:addStatusEffect(EFFECT_SIGNET,0,0,18000);
	end
`end;``

**Comment by metalfiiish** [comment]
This can be closed, fixed in recent PR.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/pull/4393
