### ISSUE TITLE
Random Packet issue multiple clients disconnected for no reason

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1588]
Randomly multiple clients over multiple zones are disconnected for no apparent reason. This morning we had no server crashes but had over 25 clients disconnect for no reason. I would speculate there is a packet issue causing these disconnects that has not been reported/fixed.

**Comment by TeoTwawki** [comment]
Looked into this a bit, and they aren't getting connection loss they are crashing client side semi randomly.

Kill mob, stand there = nothing happens. Kill mob, start to walk away before its body hits the dirt = CRASH.

**Comment by xdemolish** [comment]
does the client only crash after walking a specific distance? or is it just if the mob isn't in view while it drops dead and char is walking?

**Comment by TeoTwawki** [comment]
Hard to say, Legion has their run speed set pretty high. I think its on 90..during one of the crashes I had been trying to figure it out I thought I hadn't moved very far and spun the camera to see another target. I have noticed thus in far every instance of this crash I personally witnessed:

1. I was moving away from the dying target
2. I had tabbed onto a new target as it died
3. I had killed it with a ws, but that ws has no problems during the fight itself so its not the ws itself at fault

Due to the somewhat random nature of this, I haven't been able to narrow it down further. I know its not a message related crash, as I was solo and had ls off with nobody around, and the mobs tp attacks all work without issue and not messages in battle are crashing.

I thought maybe people were running out of exp range as the exe message was hitting the client, but that hits screen before the crash. It really looks more related to the view than distance but I just can't be certain yet.

**Comment by TeoTwawki** [comment]
..I'm not actually sure why (or if) visibility would even be *able* to cause such a thing.

**Comment by xdemolish** [comment]
i dont even know, just that i remember getting client crashes at some point when looking at certain areas in zones on 2005 vanadiel collection (prolly corrupted files)

**Comment by R3P0FFXI** [comment]
25 people do not have corrupt files, and its a different 25+ every time. If It was one person i would agree on the files but this happens to everyone very randomly.

**Comment by takhlaq** [comment]
does this still happen

**Comment by TeoTwawki** [comment]
somewhat. abyssea attowha near where the gas walls should be but arent. while killing the crawlers. thats a fairly likely place to get it to happen.

**Comment by TeoTwawki** [comment]
maybe the client expects thise npcs to be there to animate them, idunno

**Comment by zynjec** [comment]
Stale, if anyone else has this problem feel free to open another issue.
