### ISSUE TITLE
Excalibur

### ISSUE THREAD

**Issue by TheMuffinPirate** [DarkstarProject/darkstar#1617]
As it is currently setup excal is coded with a 15% base proc rate on the added effect scaling down to 5% based on level difference. Testing from retail suggests that the proc rate is not effected by level difference but is closer to 10% regardless of target.

**Comment by TeoTwawki** [comment]
All melee add effects do not level correct, and whoever put a level correction check there was wrong.

**Comment by TeoTwawki** [comment]
I just looked.. @nesstea wanna fix your script? the animation isn't correct either.

**Comment by SearainGaruda** [comment]
despite the fact that Excalibur additional effect/multiplier are, apparently, very well documented I've been looking for a confirmation and finally managed to get a hold of Tekki, one of the first NA players to get Excalibur in retail, back in 2006) through PM on BG forums, here's what he told me:

    Re: Excalibur info

        I have data, somewhere (...). its on an old hard drive somewhere. I can see if I can find it sometime next week (Right now I'm at my busiest with work) It was parses from countless Tiamats (Tiamat provided the best data for Excalibur. I received the sword just as BRD tanking was taking off, so my LS was able to allow me to focus on an Excalibur build, instead of tanking)

        "The proc rate of the additional damage was exactly 10%"

        "The damage of the additional damage was equal to 25% of your current HP"

        "The 2.5 damage multiplier was about a 5% proc rate "

These info match 100% what's out there on the web.

In addition to this, here's some more info I got from a former LS member (I played retail between 2003 and 2008) who used to own the sword:

"The additional effect is, for all intents and purposes, physical damage (slashing damage, to be precise) and ignores defense completely."

Hope it helps, it'd be great to have a fully functioning Excalibur on DSP servers!

**Comment by Deadwing888** [comment]
I've got one, and can confirm proc rate if it is deemed necessary.

**Comment by TeoTwawki** [comment]
@Deadwing888 proc rates have been confirmed to be in the ballpark of 10% for add effect already  (I saw one saying 9 point something..and sample size and randomness always leave a margin of error in parsing). I haven't seen any data on the 2.5x dmg proc aside from the post by @SearainGaruda above saying 5% which goes is way off from the databases current 16% so confirming that would be a help. I thought the % proc dsp had in the core before I moved it to the database had a reliable source but I can't find one at the moment at all on the web..Neither wiki says anything so must have been from some age old bg forum post.

**Comment by TeoTwawki** [comment]
If the proc rate dsp is using for the 2.5x dmg proc is confirmed wrong, this is the line to adjust https://github.com/DarkstarProject/darkstar/blob/e41c17615cdbcba03023f5961b875fd93e84e1fe/sql/item_mods.sql#L19639

**Comment by SearainGaruda** [comment]
@TeoTwawki the 2-2.5x damage multiplier proc rate should be the same across all relic weapons I believe and it was estimated to be around 5% back in the days (I'll scavenge the BG forums later to find proof of this). Was this changed in retail at some point?

So, if it's 16% on DSP for all weapons, by all means leave it as is, bringing Excalibur to 5% while every other weapon stays at 16% would be a massive nerf.

Also, on DSP the damage multiplier for Excalibur is currently set at 2x (or at least that was the case til a few weeks ago) instead of 2.5x for some reason.

@Deadwing888 it'd be great if you could get out there on your retail server and get some actual numbers. Do you have any other relic? Just to test if the damage multiplier proc rate is actually the same for all the relic weapons.

**Comment by TeoTwawki** [comment]
@SearainGaruda ist actually 2.5 in db https://github.com/DarkstarProject/darkstar/blob/e41c17615cdbcba03023f5961b875fd93e84e1fe/sql/item_mods.sql#L19650

I didn't check if what was there was right at all, I just moved them to being a modifier instead of static item ID checks in a switch statement so it'd be simpler to add the newer lv 80/85/90/95/99 relic weapons later (which I never got around to actually finishing those myself, so if anyone wants to volunteer, have at it). Original source for 16% was ffxiclopedia (I had forgotten, had to look up my own pull request form back then) https://github.com/DarkstarProject/darkstar/pull/877/files#diff-cc985bfb331ab7e7b96d5eac26305e10L157 

Did more digging once I new the source and looking at several of ffxiclopedias talk pages, this is probably incorrect and users were posting different information to different relic pages and stating its the same for all relics without the data to back that up...Excalibur's talk page says 5% for all relics, while Gungnir's says 15% and another relic's page says 10.6%...Seems likely some of these people were eyeballing rather than actually doing the math with a realistic sample size or they aren't all the same proc rates for all relics.

**Comment by SearainGaruda** [comment]
Could this be helpful? http://www.bluegartr.com/threads/84032-Relics-Xtimes-damage-proc-rate-testings

More to come though as I'm going through 200 pages worth of threads on the XI forums on BG, it's gonna take a while.

**Comment by TheMuffinPirate** [comment]
Regarding the damage multiplier it is set to 2.5x but only producing 2.0x times damage for some reason

**Comment by TeoTwawki** [comment]
> it is set to 2.5x but only producing 2.0x times damage for some reason
Damage is literally being multiplied, so that not possible.
The mod value is 250 and /100 to get the multiplier value.
damage = base damage * multiplier.
**250 / 100 = 2.5**
Remember that there is always a degree of randomness in damage numbers, so maybe your non procs are rolling high and your procs dmg rolling low.

**Comment by TeoTwawki** [comment]
> it is set to 2.5x but only producing 2.0x times damage for some reason

Damage is literally being multiplied, so that not possible.
The mod value is 250 and /100 to get the multiplier value.
damage = base damage * multiplier.
**250 / 100 = 2.5**
Remember that there is always a degree of randomness in damage numbers, so maybe your non procs are rolling high and your procs dmg rolling low.

**Comment by TheMuffinPirate** [comment]
Ill investigate the damage multipler more but regardless of that, we know for certain the add effect proc rate should be a constant 10 right?

**Comment by TeoTwawki** [comment]
@TheMuffinPirate  we know its not level corrected (on retail you'll get the same rate vs lv0 mob as vs lv50 mob, etc)

**Comment by SearainGaruda** [comment]
both Tekki's numbers and the data in that BG thread pretty much confirms that it isn't 16% for any of the relic weapons but much less, it's pretty safe to assume that x2-2.5 damage procs about 5% of the time for all relic weapons.

Some of the players posting in that thread provided much of the info we relied upon to figure out stuff back in the days (like Kirschy and his Haste research).

Also, Tekki used to be one of the most prominent NA players around 2005-2007, he also used to have a blog with all the Excalibur data and parses (as he was probably the first NA player to turn his PLD into a HNM DD with it) and he was and still is a mod on BG forums...I have no idea why you'd be so skeptical of his data but then let someone put level correction on add effects.

Also, I can assure you that, in game, Excalibur is doing 2x damage and not 2.5x, I'll find a way to prove it through a parser in the next few days.

**Comment by TeoTwawki** [comment]
If someone wants to open a pull request for removing the level correction and changing relics proc rates in item_mods.sql have at it. ness must be either away, busy, or not interested and I'm buried in non ffxi related work atm.

>Also, Tekki used to be one of the most prominent NA players around 2005-2007, he also used to have a blog with all the Excalibur data and parses (as he was probably the first NA player to turn his PLD into a HNM DD with it) and he was and still is a mod on BG forums...I have no idea why we'd be so skeptical of his data but then let someone put level correction on add effects.

Who's we? Its unlikely the devs even saw his data, and trusted whoever was making putting that 16% there back in the day (that code was seriously mega old dude). Just like I trusted existing code to not be totally bogus when I was only moving the value to a new place, till I was shown different.

**Comment by teschnei** [comment]
Pretty sure 16% is the proc rate of level 99 relics

**Comment by TeoTwawki** [comment]
@teschnei maybe. when I moved it to a mod tho dsp only had the lv75 relics in though.

**Comment by TheMuffinPirate** [comment]
I submitted a pull to remove the level correction and set the rate to 10%, will do a separate one for the damage multiplier activation when we have more concrete information

**Comment by Deadwing888** [comment]
Hopping onto retail now to parse it

**Comment by SearainGaruda** [comment]
It's very likely that it's 5% and 10% but the sample size just isn't large enough. It'd absolutely make sense, I doubt SE nerfed it since Tekki's parses on Tiamat back in 2006-7. 2.5x certainly isn't 16% though, never was.

**Comment by TeoTwawki** [comment]
The other relics likely need same adjustments not only for that erroneous 16% proc on dmg multiplier, but for any additional effect in script as well. I think they all went in around same time.

**Comment by Deadwing888** [comment]
Yeah idk what to tell you, unless it's higher for pld than rdm.

I did 5 sets of 200 and in not one of those sets did it make it to 10%. I'm personally pretty convinced it's lower (at least for rdm), 1000 hits is a fair amount.

**Comment by SearainGaruda** [comment]
I'm no math buff but Isn't the margin of error on sets of 200 still pretty
big? 3~ and 7~ % on 200*5 swings probably doesn't rule out the possibility
of it being 5 and 10 (also due to the fact that other relics were reported
around thos numbers), a set of 10k swings would prolly be ideal but I don't
see anyone wasting that much time on such a trivial issue. I'll try to get
Tekki to scavenge those parses from his old blog/pc.
On Jul 3, 2015 4:58 AM, "Deadwing888" <notifications@github.com> wrote:
>
> Yeah idk what to tell you, unless it's higher for pld than rdm.
>
> I did 5 sets of 200 and in not one of those sets did it make it to 10%.
I'm personally pretty convinced it's lower (at least for rdm), 1000 hits is
a fair amount.

**Comment by SearainGaruda** [comment]
Also do you mind posting a raw data text file and the kparser file so we can make a comparison with Tekki's data and figure out if something's changed since toau?

**Comment by Deadwing888** [comment]
This is the best I can do:

https://dl.dropboxusercontent.com/u/42436114/IMG_4439.JPG

**Comment by TeoTwawki** [comment]
In regard to the damage multiplier of 2.5 resulting in 2.0 times damage: the only thing I can think of that could theoretically make that a possibility, is something needing cast as a float that is currently an int, resulting in the value after the decimal being shaved off.

As for the proc rates, I'm sorry but pencil and paper photo is not what we mean by parsing. 5 and 10 for the proc rates on lv75 relics seems more reasonable than the previous 16 and 15 with what info we currently have. Also Kj's inbox is gonna beg for mercy soon, every post here send him an email. Should discuss on irc or the dsp forum if we need to.

**Comment by teschnei** [comment]
I like to keep in the loop, it'd be whasf complaining if any

**Comment by TeoTwawki** [comment]
Oh well, carry on then!
  *hides from whasf*

**Comment by TeoTwawki** [comment]
With teschnei's help I think I've found and fixed the problem you guys were talking about with the 2.5 multiplier only giving 2x damage. #1652
