### ISSUE TITLE
Crash of Unknown Cause

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1649]
https://www.dropbox.com/s/srz6rvqj77lhe6i/crash%20of%20unknown%20cause.7z?dl=0

**Comment by xdemolish** [comment]
something changing the player's zone as they're zoning (it'll only occur on multi-process setups)

though im not sure how that's even possible anymore since there's a trigger set up to prevent that from happening (https://github.com/DarkstarProject/darkstar/commit/00011c7dffadd5fbaa6b0335f5ff1b2afdf6cb3e)

**Comment by xdemolish** [comment]
you either included the wrong logs, or the crash occurs on a char logging in and not just zoning
if it's the latter, i think i got dis

**Comment by R3P0FFXI** [comment]
Demo please talk to Teo regarding this issue

**Comment by TeoTwawki** [comment]
@R3P0FFXI I already got with him on IRC

**Comment by xdemolish** [comment]
i dedicated a whole branch to bugs i cant reproduce reliably just for you
pull from https://github.com/DarkstarProject/darkstar/tree/dev and see if it still occurs
