### ISSUE TITLE
Maat's Cap SMN fight

### ISSUE THREAD

**Issue by Turttle** [DarkstarProject/darkstar#1870]
If the pet keeps auto attacking Maat and kills him while the ending CS plays (cant move) it does not count as a win for the Maat's cap quest.

**Comment by xdemolish** [comment]
prolly gonna fix once i finish rewriting bcnms

**Comment by TeoTwawki** [comment]
That is hilarious.
"***Way to go, Carbuncle!*** *We were supposed to defeat the old man, not murder him! Those front paws better be good at digging, we have to get rid of the body before we head back to Jeuno*."

**Comment by bendangelo** [comment]
This fixed or being worked on?

**Comment by TeoTwawki** [comment]
Nope, demo gave up on BCNM because he had to stop and ask what retail behavior was every 5 seconds (the nasty **old** code prolly gave him to much of a headache too). Offhand it sounds like Maat's not being hit by BCNM cleanup which would be same issue as his pet that kept getting left behind before. Prolly wrong/missing value in an sql table. Last I checked all the other BCNM had their stuff depop immediately when win/lose condition is met, not after cs finish.

**Comment by nesstea** [comment]
Demo had some ERA code he was going to DSP-ify but never finished it.

**Comment by xdemolish** [comment]
that was ENMs, and i sent code to era cause minions but they all died on me after a ghetto implementation of one of the ENMs so that died too

**Comment by xdemolish** [comment]
in other words: no era code for me to DSP-ify

**Comment by nesstea** [comment]
sad panda
