### ISSUE TITLE
Magic damage not breaking bind effect (with details)

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2028]
In day-to-day play on a darkstar server, bind holding through magic damage is the number one thing obviously off from retail.

After a few hours of testing I've nailed down these specifics:

Magic damage from nukes have a chance to break bind.
DOT spells that do initial damage have a chance to break bind. (yes dia, yes bio, no poison)
Being hit and having spikes deal damage has a chance to break bind.
The chance to break bind does not vary based on how much damage is done.
The chance to break bind does not vary based on macc or player int vs mob int.
The chance to break bind does vary based on your level checked against the mob's level.

My testing indicated the chance for magic damage to break bind based on level go like this:

Too weak- 0% chance to break
Easy Prey- 15% chance
Decent Challenge- 15% chance
Even Match- 30% chance 
Tough- 75% chance
Very Tough- 100% chance
Incredibly Touch- 100% chance

Now, I believe in the past I've seen bind hold on an IT vs a nuke, but in two hours of testing I couldn't recreate that. If it were capped at 5% chance to hold and 95% chance to break on each end I don't think that would be the end of the world. I also don't think it would be the end of the world if it functioned based on an int check of player vs mob, but it would need to ramp up to 95% very quickly once mob int was higher than player int. If anyone has any questions I'd be happy to go back in and do more testing.

**Comment by TeoTwawki** [comment]
> Now, I believe in the past I've seen bind hold on an IT vs a nuke, but in two hours of testing I couldn't recreate that. 

Retail has it being a stupidly rare occurrence. DSP does have a bind break chance, its just a status flat % for now instead of being calculated though.

> The chance to break bind does not vary based on how much damage is done.

I am very certain it **does**, in a very small and meaningless way (good old SE..). Its trumped by the level correction involved. Nothing matters nearly as much as that level difference when it comes to "will the next nuke/melee attack break it?" (the answer is going to be yes anyway, on anything that matters, barring crazy luck - as you saw on your VT and IT attempts even a 1dmg dia is going to break that 199 or 200 tries).

**Comment by Deadwing888** [comment]
I was not aware DSP had a bind break chance coded for magic. I admit my test server build is a month or so old, but I found it impossible to break bind with nukes there, ditto on nasomi where I regularly play.

If you're certain it does, you're certain it does, but I eyeballed absolutely no difference between bio for 20 stone for 200 and thunder 3 for 800 in an hour of playing with the same mob.

**Comment by TeoTwawki** [comment]
I suspect that its not always actually working. because if I remember right it was hardcoded to something like 30% ish bust doesn't seem to even be breaking 3/10 binds.

And as for the dmg thing there is no way you are going to get a large enough sample size comparing a low enough dmg nuke vs a "normal ish" nuke on a low enough lv mob with spending months on it, to notice it.

And yes I'm certain. go ahead and eyeball it for about 4 more years. Comparing a sub 100 dmg stone one to thundaga4, or something. Or you can read the rest of that paragraph instead of trying to eyeball a small sample size and declare a fact when its totally irrelevant: on anything **that matters** you should expect bind to break anyways. Whatever the actual math is, your chances of not breaking it will always be astronomically low.

**Comment by xdemolish** [comment]
> but I eyeballed absolutely no difference
1) shit how'd you manage to eyeball it for 200 attempts
2) just write a plugin to spam shit and parse the info and leave it running on retail or something so we know it's as accurate as we can get it

**Comment by Deadwing888** [comment]
I may go back and do some more testing on damage amount or I may not. 

I know we all agree damage dealt is not a big factor, but if it was a factor at all you would think it would be visible to the naked eye from 2 damage spikes vs 800 damage nukes, I mean goodness that's more than two orders of magnitude.

In response to xdemolish, I spent about four hours eyeballing total and don't mind doing it because I feel like I'm in a good position to bring you guys information you need. Scripting is out of the question on anything harder than decent challenge because the mob would kill me. 

I could do some parses with larger sample size if it's really needed but in my view this has been 100% off for two years, so if I can provide info that gets it within 90% then I've done my job. Plus last time I parsed 1000 hits of my excal that indicated a 7% hp dmg proc rate everyone was like "ahhh yeah but I'm sure it's 10% so let's just leave it at that"

**Comment by TeoTwawki** [comment]
My point was: SE likes to do stupid shit. Its really not worth reverse engineering whatever nonsense SE does to figure out a minuscule difference you aren't going to notice without going way out of your way to look for it. 

Do a level compare and call it a day until some board to death BG math guru decides to parse out thousands of nukes in an attempt to figure out exactly what SE does. But do not come here and tell me you eyeballed it and this is so.

Frankly I find the idea that someone should implement something to the spec of "I spent an hour in retail today, I now know all about it and you may consult my expertness" to be offensive. When multiple persons asked you to parse the Excalibur thing **you posted a picture of your writing on paper**. 

My opinion of your credibility is nosediving from you even having the balls to bring that up. Your numbers didn't match any known source, and we should change stuff to be based on your non parse?

As a general policy nobody just takes anyone word for anything parses are less likely to have either of human error or totally guess bullshit. Tell me again how Simurg  and Roc always have capped hitrate.

**Comment by Deadwing888** [comment]
We've all heard a lot of people say a lot of things about XI, I believe what I see when I play. Nowhere here do I feel like I've crowned myself some expert on bind mechanics, I just want to be able to go up and farm diorite and have it not be a snooze fest due to incomplete bind code. Everyone I play with complains about it, and I'm actually here trying to help.

I'm a Lighting Designer by profession and when we light scenes we focus on getting the big brushstrokes right first and fine tune in later rehearsals. Yeah I'll give you the simurgh thing, I hadn't tested a 99 thf stacking eva, but I went back and did so when you contested my information so I don't see the big deal here.

**Comment by TeoTwawki** [comment]
If you go back and look at it, nowhere did I say we should try and actually implement a dmg check on this...I used that quoted sentence to point out that nothing but the level difference is really important at this time. Yet every post since has been about you not seeing dmg effect it. 

**Its not enough to for me to know something from experience, I gotta be able to prove it to really call it retail or I'm generally not allowed to implement it.** There are some exceptions (like this one) when the exact math can't be reasonably figured out and or its an acceptable temporary departure. We couldn't even add a modifier for sharpshot acc bonus without pics proving how the acc is added. 

The "big deal" was wasting my time reading github notifications to see you acting like a trivial part your info was both right and simply dismissed, and not comprehending that your data isn't data at all its just you saying what you saw. My certainty of the opposite? Also me just saying what I saw. "*Parses or it didn't happen*" for the both of us, if that helps.

**Comment by Hozu** [comment]
Unless magic breaking bind is recent (in which case idk how I missed it), I can be 99% certain that if it's there, it's not working. I would really, really like this to be a thing.

**Comment by teschnei** [comment]
thanks for the emails about your bickering, please do it somewhere else in the future (or not at all)

if the only thing that seemed to matter over hours of testing was level difference, then we can reasonably say that level difference is the only thing we need to care about

Teo: if thunder6 and bio have the same chance to break bind, even if it's only over 100 or so casts, it is more likely that damage has nothing to do with it than it does.  if you'd like to dispute this, I'm on IRC

Deadwing: if a DC mob is killing you, you probably should summon your trusts or use a better bot. in response to excalibur, I don't think I personally saw that, so if you can make a pull request with the data to back it up, I will look at it (I don't really trust any of the wikis for a lot of mechanics)

Now, as to the current bind mechanics... physical attacks (so melee and ranged) and weaponskills have a 40% chance to break bind, and spells do not check bind at all

**Comment by TeoTwawki** [comment]
@teschnei  #1617

**Comment by TeoTwawki** [comment]
"Fixed" using deadwings numbers (can be adjusted and/or changed to a proper level calculation later) in PR #2033

I apologize for behaving rather unprofessionally, retaliating by bringing up Simurg in response to Excalibur, and also for ever even pointing at the effing damage comment. 

> "Parses or it didn't happen"

As much as I hate apologies that contain a "but" this one has one: but I feel my points I *tried* to make are still valid, even if the way I went about it was bad. WOOSH to anyone that still thinks all this was about the damage.

.
> I suspect that its not always actually working. because if I remember right it was hardcoded to something like 30% ish bust doesn't seem to even be breaking 3/10 binds.

> Unless magic breaking bind is recent (in which case idk how I missed it), I can be 99% certain that if it's there, it's not working. I would really, really like this to be a thing.

> Now, as to the current bind mechanics... physical attacks (so melee and ranged) and weaponskills have a 40% chance to break bind, and spells do not check bind at all

Additional apology: for being totally effing wrong about magic break being even partly coded (I thought max got as far as setting it to be a flat rate along with the melee). I should have actually looked before even opening my mouth.

**Comment by Hozu** [comment]
Didn't #2033 fix this?

**Comment by TeoTwawki** [comment]
Yeah just this never got closed after.
