### ISSUE TITLE
King Behemoth Using Wrong Script

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#2096]
King Behemoth is not using the meteor script located in mobskills. It is using the spell "meteor" as can be seen in mob_spell_lists.sql. That is why the meteor it is casting is doing much less damage than expected.

**Comment by teschnei** [comment]
Why would he use the mobskill?

**Comment by Zenny89** [comment]
What's the point of the mobskill then?

**Comment by teschnei** [comment]
For the mobs who have a mobskill called Meteor (Chlevnik)

**Comment by Zenny89** [comment]
According to here: http://ffxiclopedia.wikia.com/wiki/Meteor
They both use the same meteor.

**Comment by teschnei** [comment]
Pretty sure King Behemoth casts the spell, because it has the spell
animation and not the "I am dying while using meteor" animation (which is
the entire reason Chlevnik has it as a mobskill, for the unique animation).

When it comes to the classification of actions, you should probably not
rely on the wikipedia for anything, as they do not inspect packets or the
client files.

**Comment by Zenny89** [comment]
Ok, how would I go about making the KB meteor do 3x the amount of damage it currently does then?

**Comment by Zenny89** [comment]
Nevermind - think I see how to.
