### ISSUE TITLE
Worms Roam Above Ground

### ISSUE THREAD

**Issue by bendangelo** [DarkstarProject/darkstar#2138]
I think everyone is familiar with this bug. Worms shouldn't be visible when roaming around.

**Comment by armouredking** [comment]
To add onto this, worms appear to link when travelling below ground. IE: I'm attacking a worm, a nearby worm decides to move - it moves into linking range, starts attacking me - but the game still thinks it is under ground. The name is not above the worm.

Yet, it can attack me from below ground but I cannot target it or attack it ( even though I can see it because they don't move underground ). Very annoying when combined with their Bind casts.

**Comment by bendangelo** [comment]
Well that's a bigger issue.

**Comment by Hozu** [comment]
Are worms even supposed to be able to aggro while underground?

**Comment by bendangelo** [comment]
Nope

**Comment by Hozu** [comment]
Might be better to have a check in aggro where if the mob has ROAMFLAG_WORM and has the name hidden to not aggro?
