### ISSUE TITLE
Login Server Randomly Locks up

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#2241]
Not sure whats causing it but randomly the login server will not accept any more connections and users when trying to connect will get 3101 errors when trying to connect. Restarting the login server does seem to resolve this issue.

**Comment by TeoTwawki** [comment]
I've seen what he's talking about in my own personal server after very long uptimes. Eventually lobby just starts failing to make connections, and you restart just the lobby portion and its back to working just fine. Not an sql prob or client prob - its just DSConnect-server.exe itself. I believe the problem is simply accumulated crap from connections that didn't get freed/cleaned up.

**Comment by bendangelo** [comment]
This isn't random, connections are probably not being garbage collected. Someone just has to look into memory leaks.

**Comment by nasomi** [comment]
This occurs after a given number of connection attempts have been made. For me it takes about 2 days. I have a job that kicks off every 24hr that kills the lobby server around 2am, which is then automatically restarted by the restarter.

**Comment by teschnei** [comment]
pretty sure bdf63acf4cc5f168bde0e92938e9b3598e482738 has nothing to do with this issue, though
