### ISSUE TITLE
Bastok 9-2 Running Away from BCNM Battle causes screen blackout.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2353]
I've tested this a few times. You can't move. Also, if you DC during the fight, it puts you right outside the  fight in an inaccessible area.

**Comment by LionelGrimm** [comment]
This happens in avatar fights as well when you run away. You have to crash your game and then when you come back, you're still stuck in the BC.

**Comment by nesstea** [comment]
TextID/MobID shifts. I wanna know how to fix this :)

**Comment by gedads** [comment]
It can be fixed manually just by opening polutils and correcting numbers but since at least a year, starlightknight use to run his script aftar each update to do it automtically leaving only new npcs to add which is much better to me.
So the best option is to wait 10 november and pray for starligknight to run his script (i think he didn't update after the last update last month or after last big update for rhapsodies but it was a small one).

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
