### ISSUE TITLE
@bring and @goto don't work on multi game server setups

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#2677]
The command can't find the player if they are not on the same game server as the GM.

**Comment by teschnei** [comment]
you can make goto fetch the pos from the database, but i don't think
there's a guarantee that it'll be up to date and the player is actually
there
for bring, that would need it's own special message, which is more work
than i'd be willing to put in for a questionably useful gm command

**Comment by TeoTwawki** [comment]
`@jail` has the same problem as `bring`. 

Its a bit annoying to have to zone across servers to find the turd antagonizing the GM logged off because he knew it'd take just long enough to load in to allow his escape, (the whole one time I've wanted to use it, so I had to database edit them into the zone and set the jailed variable instead). I think it'd just be better to have an offline version of the jail command than to try and write out a way to try and make it work cross server though. Maybe I'll do that next time I'm bored.

**Comment by TeoTwawki** [comment]
@takhlaq

**Comment by takhlaq** [comment]
oops forgot there was even an issue for this
