### ISSUE TITLE
Serket's Regen(Too high)

### ISSUE THREAD

**Issue by LionelGrimm** [DarkstarProject/darkstar#2711]
Play on a 75cap server, the Regen is way way higher than it used to be. It is so high that certain jobs that could easily solo it at 75 cap need to dual box it. I am not sure if this has ever been looked into or reported but something is way off here.

**Comment by dazusu** [comment]
This is way too open ended.

At what 'era' of level 75 could a single person 'easily solo' Serket? Back at 75 in 2005, it would take 6+ well skilled players; and gradually this decreased as more expansions were released, new jobs became available and abilities/jobs were adjusted. 

The regen can be modified for the specific era of the server you're playing on; I found myself that all HNMs/Ground Kings on DSP are way too weak (If going for that classic 75 feel)

**Comment by LionelGrimm** [comment]
THFS and RDM's were soloing Serket back in late 2005 at 75cap. I don't know what server you were on but there were plenty of soloers on my server. I soloed it regularly and the regen was NEVER this high, it is almost as high as KV.

**Comment by helixhamin** [comment]
Hint: The request will go no where if you cannot show hard numbers. General statements don't help. A spreadsheet showing old regen values compared (total damage, total hp, total kill time, total damage until death - total health = regen / time = regen per tick) to new regen values through testing and proving will get attention. Sorry, but "seems" and "feels" and anecdotes do not really help to identify the proper values...

**Comment by TeoTwawki** [comment]
solo'ing on those jobs was not easy, it was possible but not easy - at best you'd come very close to raging it. I camped it extensively on retail from 2004-2008 and to consistently keep my damage far enough ahead of its regen to not rage it, I always need at least both a signal pearl and a tactics pearl (after those existed) or a duo buddy. As helix said, need hard numbers - need data on the regen value, and not anecdotal accounts of it being too hard, in order to adjust the regen values on this mob. **I don't doubt that its probably wrong, but without info nobody knows what to adjust it too.**

**Comment by zynjec** [comment]
No real proof regen is too high, and it was meant to be hard at 75. Closing.
