### ISSUE TITLE
Mobs with 2hrs don't use them.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2752]
During the testing of my latest pull, I noticed that they weren't using the ability as I was smacking the master (to death) with a Kraken Club. I ended up having to force a magical move to ensure my code didn't cause a problem.

**Comment by bendangelo** [comment]
This is a big problem, parties need to wipe. Will fix soon.

**Comment by Hozu** [comment]
Renaming because no mobs with 2hrs use them.

**Comment by abriasffxi** [comment]
Hopeful of a fix here.  Any data or testing or anything that could help?

**Comment by Kushdr** [comment]
Not sure if this was intentional as part of the AI rewrite or not, but I'm pretty sure it's just this line in Mob_controller.cpp (line 298)
if (!PMobSkill->isTwoHour() && luautils::OnMobSkillCheck(PActionTarget, PMob, PMobSkill) == 0) //A script says that the move in question is valid

I would think if we remove the isTwoHour check it would stop caring and allow it but I haven't had a chance to test it

**Comment by nyczducky** [comment]
I know scripted 2hrs are working.

**Comment by ffxisf** [comment]
fix SMN Astral Flow

**Comment by TeoTwawki** [comment]
All the ones using mobmod 2hr need converted to use the new mixin method
