### ISSUE TITLE
infrasonics and ultrasonics are setting evasion to 0

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#2767]
printed to player and console and evasion read as zero when under the effect of these mob skills, normally evasion reads near 300 at 75.

**Comment by Deadwing888** [comment]
May want to look at lunar roar while you're at it.

**Comment by Hozu** [comment]
On a related note, evasion boost status does nothing, according to /checkparam. Accuracy boost/down is also handled as a % change instead of a flat change, making things like Distract stupidly powerful.

**Comment by teschnei** [comment]
I already removed ACCP/EVAP/RACCP as of 15 minutes ago, but it'll break a
few food scripts that I don't feel like fixing (they are supposed to be
using mod_food_xxxp).  Since acc and evasion are already percentages, a
percentage of a percentage is both wrong and retarded - especially when
things like distract are clearly documented how they function.  Anyways, I
imagine it'll fix the issue here, though I probably won't test it (as soon
as I figure out what to do with double weakness)
