### ISSUE TITLE
Aura Pots taking 0 elemental damage

### ISSUE THREAD

**Issue by ZariusCane** [DarkstarProject/darkstar#2812]
**_Client Version_** (type `/ver` in game) **:**
30151215_0

**_Server Version_** (type `@revision` in game) **:**

unknown
**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Was trying to farm sky for water earlier, noticed no direct magic damage was causing any damage to Aura Pots.  Fire,Thunder,Ice, Water, ga-3, would hit for 0 damage.  Elemental dots would stick. This was occurring when pots are not under the effect of Spectral Barrier.

**Comment by Hozu** [comment]
That should have been resolved in this commit: https://github.com/DarkstarProject/darkstar/commit/9d3b2af750d454287e140d5dc2a0f614ba45476d Was it not? Or are you using an earlier build?

**Comment by helixhamin** [comment]
@Hozu Notice the date of his client. Unless someone modified version.info, then he is on an old build.
@ZariusCane Please update the server and try again. If you are on someone else's server, then mention this to them, since until verified, it will be assumed there is no issue with the current DSP code.

**Comment by teschnei** [comment]
closing this for old client and revision
