### ISSUE TITLE
Sic does nothing with Jug pets.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2824]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/462bccce75d35e71c9c41cdeb5f25b1cd9ca450a

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
For charmed mobs it queues the random mobskill, but for jug pets it does nothing.

**Comment by teschnei** [comment]
Isn't that expected? Charmed pets get Sic, jug pets get Ready

**Comment by bendangelo** [comment]
Sic still works on jug pets.

**Comment by RwNigma** [comment]
http://www.playonline.com/pcd/topics/ff11us/detail/4975/detail.html

According to this "sic" gets replaced with "ready" and ready has charges similar too scholar stratagem.

**Comment by teschnei** [comment]
No, Sic does not work on jug pets.  You don't even get the ability in your list, and it shares a recast with Ready (which we don't actually have implemented, but still).

It is possible to make Sic work on jug pets until Ready is implemented, though. It probably doesn't work because pet types have their automatic weaponskilling turned off (in pet_controller's constructor) and the call to pick a random weaponskill is checking that.

**Comment by Topace1** [comment]
It would be great if sic could work like ready for the time being to make bst actually usefully

**Comment by teschnei** [comment]
I'm not going to spend time on making something work that shouldn't work, sorry.  I will look at implementing Ready instead, though.

**Comment by Topace1** [comment]
Thanks.
