### ISSUE TITLE
addkeyitem() & haskeyitem() don't work for Key Items over 2559

### ISSUE THREAD

**Issue by ibm2431** [DarkstarProject/darkstar#3261]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160602_0

**_Server Version_** (type `@revision` in game) **:** b1af3dc5c40e0d1bd859c28db210378466d89a7b

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

player:addkeyitem() and player:haskeyitem() don't work for key items with values over 2559. Can't add/save, or check against them. Game server throws out `[Error] hasBit: value (id here) is out of range.`

I tried looking into it, but can't seem to find anywhere a max value is explicitly defined. I suspect it might have something to do with the size of the Keys_Table in [key_items.h](https://github.com/DarkstarProject/darkstar/blob/master/src/map/packets/key_items.h) and [key_items.cpp](https://github.com/DarkstarProject/darkstar/blob/master/src/map/packets/key_items.cpp).

**Comment by aizenmyou** [comment]
I ran into this exact same issue a few months back trying to implement the Magicked astrolabe for the Necro doors, then ran out of time (between work and family) to find anything in the code to increment the max hasbit value.

**Comment by aizenmyou** [comment]
@ibm2431 I've done some tracing and if you loook utils.cpp inside the hasBit() function and see the if() condition is saying value >= size * 8. Currently size * 8 is **2560** (size is currently 320 btw) so it fails the condition.

You probably should increase the size instead of the multiplier, which comes from PChar->keys.keysList which is in mmo.h and I'm not sure if the reason, but it feels no one has touched this for a very long time and the keyitems have increase in game. Hope that helps :)

**Comment by aizenmyou** [comment]
Couldn't sleep and I used Magicked Astrolabe (KI #2578) and it works when I increased from 320 to 326.
Item is now stored.

![img_20160713_222847](https://cloud.githubusercontent.com/assets/4256716/16827151/67ef0bc8-4949-11e6-927e-94d439ab9049.png)

**Comment by ibm2431** [comment]
Apologies for delayed response, was out of town this past week.

Does this store it on the server, and can be checked by scripts? I know nothing about how KIs are stored server-side.

Seems like a conveniently easy fix if so!

**Comment by aizenmyou** [comment]
@ibm2431 Ok I forgot to mention, you will need to also modify the key_items.h and add KEY_TABLE_% and the change the MAX_KEYS_TABLE from 5 to 6 otherwise you will not see it in your KI's since there needs to be more room to store the keys from the DB.

If you look at my last two commits in my DSP branch, you can see the changes needed for higher Key Item values. I just haven't found the time to update them here in the main DSP - https://github.com/aizenmyou/darkstar/commits/master

**Comment by teschnei** [comment]
Fixed with 7d749f63272592c7c6b4bc01bca6f07a24cb90c2.
