### ISSUE TITLE
Voidwatch does not work.

### ISSUE THREAD

**Issue by sephirothdane** [DarkstarProject/darkstar#3487]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
Revision: unknown

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
I have already enabled all the expansions and I also turned on ENABLE_VOIDWATCH = 1, but nothing happens when I talk to VoidWatch officers, or when I check the Planar Rifts. When I checked the DSGame-server.exe log, it shows both Planar_Rift.lua and Voidwatch_Purveyor.lua files are missing in the scripts/zone folders. How am I able to get this working? Is there a place where I can download these files?
Thank you for any advice!

**Comment by teschnei** [comment]
there is no voidwatch implementation yet, and there's nowhere to download the files (the ENABLE just controls whether the NPCs spawn or not).  we don't have a timeframe for voidwatch yet, either (after abyssea, wotg, and the rest of toau, probably).

i'll close this because it's too broad to be useful for the developers for issue tracking, but thanks for bringing it up at least once so it'll show in searches
