### ISSUE TITLE
Summoner Avatars remain after dismissing.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3516]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

30161004_1
**_Server Version_** (type `@revision` in game) **:**

ed0d506
**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
After dismissing avatars, they "stayed summoned" and can take dmg from mob AoE moves.

Reproduction:

 - Summon avatar/ elemental spirit.
- Dismiss said avatar/elemental spirit.
- Profit

http://prnt.sc/d1wxtf

http://prnt.sc/d1wyhm

**Comment by thedraked** [comment]
Not sure if this is the root of the issue, but the dismissed avatar's have HP remaining and if you take their hp down to 0 then they completely disappear.  This issue also happens when you zone.  

My simple fix was to insert: 
PPet->addHP(-10000);
https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/petutils.cpp#L942

Havent had much time to test it, but it seems to fix the problem.
