### ISSUE TITLE
Dynamis Statues r Unattackable

### ISSUE THREAD

**Issue by Foxm** [DarkstarProject/darkstar#3596]
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161206_3

**_Server Version_** (type `@revision` in game) **:**
71862369ae4431bdbb9613bedf2d3c75c56a7de

**_Source Branch_** (master/stable) **:**
IDK. Guess N/A

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
The following is occuring on Oldschool server:

Upon first entry Dynamis appears to work normally. However, when the following conditions occur dynamis statues "lock" and become unattackable. For example:
- Foxm casts thunder IV but statue resists spell thereby summoning additional mobs and aggroing Foxm. Upon Foxm's return to dynamis (after either dieing, home pointing, or warping out) that same statue and the rest of the statues in the zone will no longer be able to be targeted and killed.  It and all the mobs around it "lock". After considerable trial and error it appears the only way the statue doesnt lock is if it returns to its original position after being aggroed and/or the statue is killed prior to homepointing/warping out.

To reproduce, aggro a statue and die from the mobs it summons. Then home point and come back.  The statue will be unable to be killed. Or leroy jenkins a bunch of statues and warp out.  Upon returning to dynamis the mobs will be unattackable.

**Comment by sisternERA** [comment]
verified it has something to do with commit 246e45e33309c2bc882fdd90dfb7669423f05a82 respawn/despawn

**Comment by nyczducky** [comment]
Also confirmed. 
30161103_1

718623696ae4431bdbb9613bedf2d3c75c56a7de

**Comment by nyczducky** [comment]
Seems to now be random mobs within Dynamis Xarc upon entering the zone. Tower NPCs do not aggro and are unattackable.

Also saw a bunch of "mob is already spawned" messages pop up in console upon entering.

Dyna zones also do not seem to be resetting properly.

**Comment by nyczducky** [comment]
Client Version: 30161227_1
Server Version: 5617271

Same issue also occurring with mobs outside of Dynamis. 

Players are reporting when kiting Dea, and if the mob resets, it is unable to be attacked.

**Comment by wrenffxi** [comment]
Did some more testing on this.

Test 1: Start server.  Enter Dyna-Xarc with Alice.  Alice registers BCNM.  Mobs are present and attackable.  Alice leaves zone via Somnial Threshhold.  DSGame-server console shows cleanup running for Dyna-Xarc.  Reenter zone with Alice.  Console spammed with "already spawned".  Mobs are not attackable.

Test 2: Start server.  Enter Dyna-Xarc with Alice.  Alice registers BCNM.  Mobs are present and attackable.  Despawnmob the first group of mobs with GM command.  Leave zone via Somnial Threshhold.  Console shows cleanup.  Reenter zone.  Lots of "Already Spawned" messages.  Now, the first group of mobs I had previously despawned are attackable, but no others are.

Test 3: Start server.  Enter Dyna-Xarc with Alice.  Alice registers BCNM.  Bring Bob into zone.  Bob does not have the requisite Key Items, so he is not added to the BCNM.  I disabled the code that would normally warp Bob out of the zone, so he remains in zone but unregistered for battlefield.  Alice leaves zone via Threshhold.  Console shows cleanup.  Reenter zone with Alice.  BCNM registered again.  No "already spawned" spam this time.  All mobs are now attackable.

So these tests show the issue seems to be that when battlefield.cpp:547 calls PMob->PAI->Despawn() when nobody is in the zone, it's not actually despawning the mobs.

**Comment by nyczducky** [comment]
Battlefield 545 = https://github.com/DarkstarProject/darkstar/blob/2abefb839101daba7f9613ca5d7bbc9d684952d1/src/map/battlefield.cpp#L545


I believe you meant:

https://github.com/DarkstarProject/darkstar/blob/2abefb839101daba7f9613ca5d7bbc9d684952d1/src/map/battlefield.cpp#L540

**Comment by wrenffxi** [comment]
Indeed. I had some comments in lines above I forgot to account for.  Fixed.

**Comment by nyczducky** [comment]
Awesome. I'll try this out tonight and report back. 

People can finally stop complaining about the lack of Dyna and inability to get relics @.@

**Comment by nyczducky** [comment]
Confirmed that this did fix the issue. Will test some more.

**Comment by Mizzguy** [comment]
Ive tested this too, and it does work. Just a heads up though from testing. If you zone in and kill stuff but everyone dc (maybe just solo players , ect) when they log back in dyna is reset. This could be exploited. They finish the run, then force dc and log in to a fresh dyna.

**Comment by helixhamin** [comment]
@Mizzguy Guess that depends what the server owner wants. Isn't retail dynamis unlimited entries now with no waiting time? I guess exploiting this would just result in something similar.

**Comment by Mizzguy** [comment]
@helixhamin well i run the server, but wanted to let who ever know what the change had done in terms of being able to exploit. It looks as if the new pr has cleaned that up or made a few extra fixes. Im happy to just have it fixed personally.

**Comment by wrenffxi** [comment]
@Mizzguy thanks for bringing it to my attention. We had people abusing it as well.  The merged PR does fix this.  Players who go in solo, clear all the stats, then attempt to force/dc to reset all the mobs will now be removed from zone.
