### ISSUE TITLE
NPC batch tools for scripted IDs are misisng stuff when updates happen

### ISSUE THREAD

**Issue by JessLand86** [DarkstarProject/darkstar#3637]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161206_3

**_Server Version_** (type `@revision` in game) **:**
ff73311e23249dccf8575ede0dcf9720493c7d1d

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
zone.lua says:
```
local manuals = {17248822,17248834,17248878};
SetFieldManual(manuals);

local vwnpc = {17248889,17248906,17248929};
SetVoidwatchNPC(vwnpc);
```

And the sql says:

```
INSERT INTO `npc_list` VALUES (17248854,'Field_Manual','Field Manual',78,289.632,-4.864,-5.926,19,50,50,0,8,32,0,3,0x0000F20800000000000000000000000000000000,0,null,0);
INSERT INTO `npc_list` VALUES (17248853,'Field_Manual','Field Manual',0,-9.975,-12.375,322.987,8,40,40,0,8,32,0,3,0x0000F20800000000000000000000000000000000,32,null,1);
INSERT INTO `npc_list` VALUES (17248852,'Field_Manual','Field Manual',227,147.968,-0.647,-313.836,18,40,40,0,8,32,0,3,0x0000F20800000000000000000000000000000000,32,null,1);
INSERT INTO `npc_list` VALUES (17248855,'Field_Parchment','Field Parchment',96,360.000,-20.500,404.000,1,40,40,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,null,1);
INSERT INTO `npc_list` VALUES (17248907,'Planar_Rift','Planar Rift',0,120,4,-440,1,40,40,0,5,100,2,3,0x00006F0900000000000000000000000000000000,2,'ABYSSEA',1);
INSERT INTO `npc_list` VALUES (17248908,'Planar_Rift','Planar Rift',0,-441,4,-357,1,40,40,0,5,100,2,3,0x00006F0900000000000000000000000000000000,2,'ABYSSEA',1);
INSERT INTO `npc_list` VALUES (17248909,'Planar_Rift','Planar Rift',0,0.001,-28,560,1,40,40,0,5,100,2,3,0x00006F0900000000000000000000000000000000,2,'ABYSSEA',1);
```

**Comment by starlightknight** [comment]
The Lua batch job does shift these ids, but only if they were already in sync with the old version before the update. If an update happened where these shifted and someone ran the npc job and committed the results, but forgot to run the lua job, they will fall out of sync - and the job can't fix them next time, because they were wrong to begin with. This is noted in the batch readme. If these get manually fixed, the batch should pick them up again next time as long as the lua job gets run

**Comment by ibm2431** [comment]
I am not at all surprised that the zone in question is West Sarutabaruta. Those IDs in the script are _really_ off, though. They're not even sequential!

**Comment by ibm2431** [comment]
@starlightknight: I'm looking at the [history of this zone](https://github.com/DarkstarProject/darkstar/commits/master/scripts/zones/West_Sarutabaruta/Zone.lua), and I'm not quite sure what's going on. I am assuming that @TeoTwawki had the correct IDs [last October](https://github.com/DarkstarProject/darkstar/blob/620f4f8b49187e75da54b7e29aab979529649264/scripts/zones/West_Sarutabaruta/Zone.lua). I did the [version update for October](https://github.com/DarkstarProject/darkstar/commit/8d55a04a5ac3c8b4ef66bf7afc3e7c4fb52e8748) a few days after, in which the Lua script batch did seemingly get run, judging by the change in a single ID in West Ronfaure. I am not sure why it changed said ID when there weren't any relevant shifts in the NPC list, but it's not the zone in question so let's ignore it for now. There were no ID shifts in West Sarutabaruta.

When I [ran the job for the November update](https://github.com/DarkstarProject/darkstar/blob/41e5068249fcb2ef4167a815c97ab97a2d884bec/scripts/zones/West_Sarutabaruta/Zone.lua), it appears to have properly shifted the 3 VW NPCs. It changed all three field manuals, but not by the same offset, and all three values were wrong anyway (judging by that [update's NPC list](https://raw.githubusercontent.com/DarkstarProject/darkstar/41e5068249fcb2ef4167a815c97ab97a2d884bec/sql/npc_list.sql), they should have been 17248869, 17248870, and 17248871).

I then did the [massive December version update](https://github.com/DarkstarProject/darkstar/blob/d405fc091a550db14f7224a277fa677d8f21faab/scripts/zones/West_Sarutabaruta/Zone.lua). The manuals should still be wrong (and were), but the VW NPCs were now incorrect as well. Not only was the offset off, but the IDs were changed from being sequential to all over the place.

**Comment by starlightknight** [comment]
@ibm2431 when you run the npc job, it wirtes out a property file in your working directory that contains a mapping of the old -> new values that the npc job wrote for each shifted npc. The lua job reads this file and does a massive regex replace in descending order. If you don't believe you're seeing the right results, glance at your copy of the shift properties before you run the npc job. 

I'm not sure what you may be observing, but i ran the job for more than a year with it accurately shifting HELM, Conquest, and FIeld manuals each update (i always glanced at the diff and made sure the numbers were right afterward). There may be some assumptions in the batch that you are running on windows/ntfs, if you're not (line seperators, ordering of files, etc). 

Note though that if the npc job shifts wrong, then the lua job will as well. If you make a manual correction in the sql afterwards, you'll have to make the same manual correction for lua, because the wrong value would have been written to the properties. It only knows what the NPC job did, because there is nothing else other than a number to compare against in lua
