### ISSUE TITLE
multiple unknown amount of mobs sharing group ids

### ISSUE THREAD

**Issue by imanthra** [DarkstarProject/darkstar#3658]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/49e650e8e95a07037225ed23b811202efdc29017

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Im just posting some of what i found here but pretty much a ton of monsters are now sharing groiup ID and PoolID it all seems to be attributed to WOTG additions starting at 17183083 in mob spawn points ending at 17183463 which is preventing monsters and NM from spawning

INSERT INTO `mob_spawn_points` VALUES (17183318,'Fiendish_Leechkeeper','Fiendish Leechkeeper',598,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183319,'Fiendish_Leechkeeper','Fiendish Leechkeeper',599,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183320,'Fiendish_Leechkeeper','Fiendish Leechkeeper',600,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183321,'Fiendish_Leechkeeper','Shadowhorn',601,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183322,'Fiendish_Leechkeeper','Shadowhorn Stormer',602,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183323,'Fiendish_Leechkeeper','Shadowhorn Stormer',603,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183324,'Shadowhorn','Shadowhorn Stormer',604,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183325,'Shadowhorn_Stormer','Shadowhorn Stormer',605,0,0,0,0);
INSERT INTO `mob_spawn_points` VALUES (17183326,'Shadowhorn_Stormer','Shadowhorn Stormer',606,0,0,0,0);

INSERT INTO `mob_groups` VALUES (598,2293,24,0,0,0,0,0,0,0,0);
INSERT INTO `mob_groups` VALUES (599,2299,24,0,128,1971,0,0,84,84,0);
INSERT INTO `mob_groups` VALUES (600,2392,24,330,0,0,0,0,49,53,0);

INSERT INTO `mob_pools` VALUES (2299,'Kurrea',58,0x0000470500000000000000000000000000000000,4,5,12,300,100,0,1,0,0,2,0,0,0,3,0,0,2,1,0,58);
INSERT INTO `mob_pools` VALUES (2293,'Kukki-Chebukki',149,0x06009C0400000000000000000000000000000000,4,1,9,240,100,0,0,0,0,2,0,32,32,157,0,0,2,1,0,149)
INSERT INTO `mob_pools` VALUES (2392,'Leshachikha',216,0x0000880100000000000000000000000000000000,1,1,7,240,100,0,0,0,1,0,0,0,449,131,0,0,0,1,0,216);
INSERT INTO `mob_pools` VALUES (2394,'Leshy',245,0x0000840100000000000000000000000000000000,1,1,7,240,100,0,0,0,0,0,0,0,258,131,0,0,0,1,0,245)

**Comment by maxtherabbit** [comment]
so this is why only 3/8 leshy are spawning in lufaise I suppose

**Comment by mikeb530** [comment]
Hello,

Is there a reason that the value of mo_id is assigned and not just auto incremented?

If not the mo_id replication can be fixed with changing the create statement to have the following



CREATE TABLE `mob_spawn_points` (
  `mobid` **_MEDIUMINT_** NOT NULL **_AUTO_INCREMENT_**,
  `mobname` varchar(24) DEFAULT NULL,
  `polutils_name` varchar(50) DEFAULT NULL,
  `groupid` int(10) unsigned NOT NULL DEFAULT '0',
  `pos_x` float(7,3) NOT NULL DEFAULT '0',
  `pos_y` float(7,3) NOT NULL DEFAULT '0',
  `pos_z` float(7,3) NOT NULL DEFAULT '0',
  `pos_rot` tinyint(3) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`mobid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=33;

**Comment by teschnei** [comment]
The mobid is set by the client. We don't pick them

**Comment by TeoTwawki** [comment]
Duplicate mobID's don't happen anyway (the table would not import in that case), this issue is groupID having been used again on the wrong mob when a new groupID should have been created for the new mob(s). group table also connect the group to the pool and drop entries, so then wrong pool gets called as well and wrong loot can drop.

**Comment by TeoTwawki** [comment]
Bonus: there are actually a few "orphaned" groupID's going unused.

**Comment by mikeb530** [comment]
Sounds good. I'll look into this.
