### ISSUE TITLE
"aftermath" effects, and how joe random contributor can help with them

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3673]
Blatantly discarding template - it is irrelevant for this. Laying it out so interested parties can tackle.

- ~~We have 4 effect scripts for this. ***four***. I don't think we need _four_ to get this right.~~ nvm, its a nightmare to condense and we don't wanna addeffectEx for the extra icons mythics apparently use

- Some scripts do `addStatusEffect(EFFECT_AFTERMATH)`

- Some other scripts do a static item ID check and a job check before calling a wrapper that applies 1 of: EFFECT_AFTERMATH_LV2, EFFECT_AFTERMATH_LV2, or EFFECT_AFTERMATH_LV3. 

  - A ton of weapons that should have aftermath effects don't because of the static itemID check, this needs to be a modifier. grab the item pointer so it can be the object you reference instead of the player, then getMod on the *item* and *not the player* to solve this.

  - The job check likely doesn't need to exist? I am aware of no situation where the aftermath is available to only one job on a weapon multiple jobs can equip who both have access to the weaponskill.

  - Effects applied by this wrapper have an unused "params" argument and defaultly fill in everything with the same power/subpower every mythic weapons aftermath is identical. these 3 effect scripts only do attack or acc or magic attack or magic accuracy.

  - Pretty sure some scripts call the version the multiple effect scripts that doesn't have the bonus's that item would grant and instead wind up with a generic default buff. Have not personally checked.

  - Empyrean WS don't have theirs set up proper yet either. So all 3 lines of uber-weapon are gimped.

**Comment by TeoTwawki** [comment]
Dear _joe random contributor_, pick a bullet point son.

**Comment by ramenkat** [comment]
- The job check likely doesn't need to exist? I am aware of no situation where the aftermath is available to only one job on a weapon multiple jobs can equip who both have access to the weapon skill. 

Take anything I say with a grain of salt, since I don't code (like at all) but ... I think you are right on this point. Any job that can equip the relic weapon should be able to gain the aftermath effect if they have access to the ws. It especially doesn't matter if the weapon is one job only (Gungnir, for example). 

/end $0.02 for joe random contributor >:3
