### ISSUE TITLE
cmbSkills set H2H for mobs that shouldnt have H2H

### ISSUE THREAD

**Issue by Neil-Mitchell** [DarkstarProject/darkstar#3674]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30161227_1**

**_Server Version_** (type `@revision` in game) **Command says unknown but i updated 2 days ago**

**_Source Branch_** (master/stable) **master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **Confirmed the tables Are borked**

This was already posted as a bug with the trait "Double Attack" but in reality its just a bunch've mobs that are set to have H2H skill thus allowing them to double attack every swing. I'm pretty new to all this coding mumbo-jumbo so wasn't sure on how to do a PR but ill post the query here for you all to see. it runs a line of code to change the cmbSkill value to its proper skill type in correlation to the mJob value for all 22 jobs as well as reducing the ccmbdmgmult to 70 from 100 so any mob listed as a mnk wont rip your face off.

```sql
UPDATE `mob_pools` SET `cmbDmgMult`='70' WHERE (`mJob`='2');

UPDATE `mob_pools` SET `cmbSkill`='6' WHERE (`mJob`='1');

UPDATE `mob_pools` SET `cmbSkill`='1' WHERE (`mJob`='2');

UPDATE `mob_pools` SET `cmbSkill`='11' WHERE (`mJob`='3');

UPDATE `mob_pools` SET `cmbSkill`='12' WHERE (`mJob`='4');

UPDATE `mob_pools` SET `cmbSkill`='3' WHERE (`mJob`='5');

UPDATE `mob_pools` SET `cmbSkill`='2' WHERE (`mJob`='6');

UPDATE `mob_pools` SET `cmbSkill`='3' WHERE (`mJob`='7');

UPDATE `mob_pools` SET `cmbSkill`='7' WHERE (`mJob`='8');

UPDATE `mob_pools` SET `cmbSkill`='5' WHERE (`mJob`='9');

UPDATE `mob_pools` SET `cmbSkill`='2' WHERE (`mJob`='10');

UPDATE `mob_pools` SET `cmbSkill`='2' WHERE (`mJob`='11');

UPDATE `mob_pools` SET `cmbSkill`='10' WHERE (`mJob`='12');

UPDATE `mob_pools` SET `cmbSkill`='9' WHERE (`mJob`='13');

UPDATE `mob_pools` SET `cmbSkill`='8' WHERE (`mJob`='14');

UPDATE `mob_pools` SET `cmbSkill`='12' WHERE (`mJob`='15');

UPDATE `mob_pools` SET `cmbSkill`='3' WHERE (`mJob`='16');

UPDATE `mob_pools` SET `cmbSkill`='2' WHERE (`mJob`='17');

UPDATE `mob_pools` SET `cmbSkill`='1' WHERE (`mJob`='18');

UPDATE `mob_pools` SET `cmbSkill`='2' WHERE (`mJob`='19');

UPDATE `mob_pools` SET `cmbSkill`='12' WHERE (`mJob`='20');

UPDATE `mob_pools` SET `cmbSkill`='4' WHERE (`mJob`='21');

UPDATE `mob_pools` SET `cmbSkill`='12' WHERE (`mJob`='22');
```

**Comment by TeoTwawki** [comment]
I wrapped your sql in code tags for you ❤️

**Comment by GMYasiinEra** [comment]
thanks alot, people were going mad over this bug on my server  so i felt it needed to be addressed..

**Comment by TeoTwawki** [comment]
Other issue, for reference for anyone that doesn't already know: #3353 
Summary: we have a column that tries to set mob damage type as if the weapon in their model is actual equipment (nawt retail). It's also checked to see if the mob should attack twice for h2h type which should *probably* be replaced by something else. Since a bunch of mobs are set to h2h skill, a bunch are attacking twice that shouldn't. _Oops._

**Comment by Hozu** [comment]
Some mobs that are set to MNK job shouldn't be attacking with "H2H" like Seiryu.

**Comment by ibm2431** [comment]
Do mobs even have jobs on retail? On SE's official retail servers, is there a column labeled "job" that each mob needs to have filled, which actually influences the mob's stats, skills, or abilities?

Players see mobs and label them as having jobs on wikis because the mobs use abilities which seem to match the player job counterparts. "Oh, the mob used Berserk. Player WARs have Berserk, so this mob must be a WAR too." The "mobs have jobs" notion is helped by the beastmen which do appear to have the same mob job counterparts that players do.

But there are _so many mobs_ which break the rules we players have. Look at the notes field for NMs post-Abyssea, and you might see a note like, "Unlike most JOB mobs, this NM has (or doesn't have) trait X". Or look no further than our trusts. King of Hearts is a RDM that casts Firaga IV. Shantotto II is a BLM who attacks with... Psychokinesis, which I highly doubt BLM has skill for (as @TeoTwawki said, mobs don't actually use weapons like we do).

Is there anything differentiating "mob jobs" on retail other than their ability list? Sure, it appears that "WHM" mobs have fewer HP than "PLD" mobs, but those HP values could just be hardset for the mobs individually, instead of calculated using a "job" value in SE's database.

Should DSP be setting mob jobs at all, or should we individually give mobs the abilities/traits they need ("MNKs" double attack)?

**Comment by teschnei** [comment]
Do you want to individually give every mob group every job trait?

**Comment by teschnei** [comment]
And don't forget that spell lists and weaponskills have nothing to do with
the job column. It's pretty much only used for traits and base stats

**Comment by TeoTwawki** [comment]
> Do mobs even have jobs on retail? On SE's official retail servers, is there a column labeled "job" that each mob needs to have filled, which actually influences the mob's stats, skills, or abilities?

@ibm2431 I'm pretty sure the answer is yes and possibly more than 2 for some mobs\*, but you can confirm most by reversing the damage calculations to figure out their base VIT and DEF for their level. And SE can easy break "the rules" by tacking on extras like black mges with more double attack than even a war would get but the mobs do have their job traits form the actual jobs (drg mobs will indeed have native acc boost trait starting at the right level). 

So there is a level of automation rather than an SE employee filling it all out. They can just override/modify whatever when they need to.

\*_A lot of mobs seemingly with 3+ jobs is simply they were given spells or 2hrs outside their jobs normal list, and folks on wiki's instantly say its a jobX_

**Comment by Hozu** [comment]
They definitely have jobs on retail. For whatever reason, crabs are PLD/PLD. Go figure.

**Comment by TeoTwawki** [comment]
> For whatever reason, crabs are PLD/PLD. Go figure.

A few crabs (usually NMs or bcnm mobs) are mnk or rdm or blm.

**Comment by GMYasiinEra** [comment]
so attention.. this fix will work for everything but 1 mob, Charybdis. make sure after you run the query to back in and manually change chary to anything but H2H other wise he going to be on PCP

**Comment by TeoTwawki** [comment]
This should be not a huge problem anymore, though we still need to decide wtf to do about the column being largely nonsensical. (which I think another issue discusses)
