### ISSUE TITLE
Sublimation eating buffs

### ISSUE THREAD

**Issue by Vanyel** [DarkstarProject/darkstar#3828]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
Multiple

**_Server Version_** (type `@revision` in game) **:**
Multiple

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
On SCH (Main or Sub) Start charging Sublimation.  Then cast Stoneskin.  Once sublimation reaches full charge it will consume Stoneskin.  
Capable of consuming Signet and all other buffs depending on the order they are cast/used in.

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/issues/1740

The bug appears every once in a while, but it hasn't been able to be fixed since nobody can figure out what causes it. Some builds it exists, while in others it doesn't appear to. Yet when it does appear, the changes made often don't even touch status effects...

**Comment by teschnei** [comment]
"searched existing issues"
