### ISSUE TITLE
Temple of Uggalepih coffer chest eating keys... must be hungry.

### ISSUE THREAD

**Issue by Heepster03** [DarkstarProject/darkstar#3871]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
Revision is: 2e31313e88aa17c60cc058a397ea3c96becaf399

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Trading a Temple of Uggalepih coffer key to the coffer chest will sometimes eat the key and give no loot.

This is the error it gives:
[11/May] [23:32:30][Error] luautils::onTrade: scripts/zones/Temple_of_Uggalepih/
npcs/Treasure_Coffer.lua:85: attempt to index local 'loot' (a nil value)

**Comment by metalfiiish** [comment]
If I read the code right it should fail to ever give loot besides any quest/AF stuff. I believe someone implemented the Treasure_Coffer.lua for Temple_of_Uggalepih without adding the appropriate loot table.

This is the file tripping your error:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Temple_of_Uggalepih/npcs/Treasure_Coffer.lua (@line 85)

Your error points to the 'loot' variable being empty, that is because it expected a list from function  chestLoot() that may have sent back no list at all:
`                    local loot = chestLoot(zone,npc);
                    -- print("loot array: "); -- debug
                    -- print("[1]", loot[1]); -- debug
                    -- print("[2]", loot[2]); -- debug
                    
                    if (loot[1]=="gil") then
                        player:addGil(loot[2]*GIL_RATE);
                        player:messageSpecial(GIL_OBTAINED,loot[2]*GIL_RATE);
                    else
                        -- Item
                        player:addItem(loot[2]);
                        player:messageSpecial(ITEM_OBTAINED,loot[2]);
end`

We can look at chestLoot() via this file:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/treasure.lua

You'll see at around line number 257, function chestLoot(zone,npc). In there you can see it builds a list of items/gil to reward based off some dictionaries built by zone id. However, there is no loot table for zone ID 159. This means any gil/object rewards should fail.

**Comment by TeoTwawki** [comment]
watch those at symbols

![line](https://user-images.githubusercontent.com/6871475/28999592-a73dc2c2-7a19-11e7-80ba-e189133e2be0.jpg)

**Comment by helixhamin** [comment]
lol, I know the devs at Line xD

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5324
