### ISSUE TITLE
phalanx ii formula fix

### ISSUE THREAD

**Issue by gori123** [DarkstarProject/darkstar#3885]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
phalanx forumula is wrong at \darkstar-master\scripts\globals\spells\phalanx_ii.lua
final = (enhskill / 25) + merits + 1;
it should be 
final = (enhskill / 25) + 3 * merits + 1;
according to http://ffxiclopedia.wikia.com/wiki/Phalanx_II

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/sql/merits.sql#L215

The fourth value in that line is the value returned by the getMerit function, multiplied by the number of merit upgrades. Since that's already 3, there isn't an issue here. Example, if someone has fully upgraded it, caster:getMerit(MERIT_PHALANX_II) would return a value of 15.

**Comment by gori123** [comment]
thank you
