### ISSUE TITLE
Cannot kick or manage Linkpearls/Pearlsacks if equipped in Linkshell2. 

### ISSUE THREAD

**Issue by Jessland86** [DarkstarProject/darkstar#3999]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170707_0

**_Server Version_** (type `@revision` in game) **:**
c4e8298ec16e5ada3b573a6de8df6b752723480e

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
If a player has a Linkpearl or Pearlsack in the number 2 slot, as a sack holder or shell holder, you can do nothing to manage these players. You cannot kick anyone if they have it equipped in number 2 slot, you cannot promote them to a sack, you cannot take their sacks away. 

So if someone is going to be booted and they know they are they can just equip the pearl or sack in number 2 slot and the only option we have is to break the Linkshell and make a new one.

**Comment by teschnei** [comment]
I pushed a fix for kicking people who have their linkpearl in slot 2.

The rest I don't know yet, the client is blocking some moves that it shouldn't be (if you, as the shell/sack holder have the LS equipped in slot 2, it seems that it won't let you do anything).

I don't remember this being an issue before, so there might be some packet changes that I don't have access to yet in order to get the client to let you do the actions if your sack/shell is in slot 2.

**Comment by Jessland86** [comment]
Just updated tonight to latest, kicking someone with pearl equipped in slot 2 crashes the server. Would have to wait till an admin is awake to see if it made a dump.

**Comment by Jessland86** [comment]
@TeoTwawki

**Comment by Jessland86** [comment]
`if (PItemLinkshell->GetLSID() != this->getID())`


[crash.zip](https://github.com/DarkstarProject/darkstar/files/1251322/crash.zip)

**Comment by teschnei** [comment]
ac3ad6e8636f79c842cd431dcdc1fe5dc8eb8f1e

**Comment by zynjec** [comment]
Looks like this was resolved.
