### ISSUE TITLE
Holy Circle duration should be 3 minutes, AF/AF+1 Bonuses not implemented

### ISSUE THREAD

**Issue by Whitechaser** [DarkstarProject/darkstar#4039]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** **:** 30170707_0

**_Server Version_** **:** Unknown

**_Source Branch_** **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
https://www.bg-wiki.com/bg/Holy_Circle

Dark Knight's Arcane Circle lasts for 3 minutes but Paladin's Holy Circle does not.
https://github.com/DarkstarProject/darkstar/blob/824fbbd7c79eea6d43524c0d96131abffac56881/scripts/globals/abilities/arcane_circle.lua

https://github.com/DarkstarProject/darkstar/blob/824fbbd7c79eea6d43524c0d96131abffac56881/scripts/globals/abilities/holy_circle.lua
(line 25 should be changed to "target:addStatusEffect(EFFECT_HOLY_CIRCLE,1,0,**180**);")

However! Neither of these two abilities take into consideration artifact armor/artifact armor +1's bonus to the duration. Should be simple though, the technique used for Flee for Thief can be copied.

https://github.com/DarkstarProject/darkstar/blob/824fbbd7c79eea6d43524c0d96131abffac56881/scripts/globals/abilities/flee.lua

So just have a variable called "buff" initialized to 180, then check the feet slot for Chaos Sollerets or Chaos Sollerets +1 for DRK (item id 14096, item id 15359) and Gallant Leggings or Gallant Leggings +1 for PLD (item id 14095, item id 15358). Add 90 to buff if they are equipped.

**Comment by wrenffxi** [comment]
You're right that the AF armor extended duration hasn't been coded yet.

You're also looking at old copies of the files.  This is the current flee script.
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/abilities/flee.lua

In this case, flee duration is extended using modifiers, rather than checking for equipped item IDs.  If you hard code an item id check, players would gain the benefit even while under the effect of level sync that drops them below item level.

**Comment by Whitechaser** [comment]
Ahh, got it! Thank you. Is there a table that shows exactly what certain modifiers return?

It looks like there aren't any modifiers for Holy Circle or Arcane Circle. Are those easy to add?

**Comment by wrenffxi** [comment]
Modifiers are detailed in comments here ...
https://github.com/DarkstarProject/darkstar/blob/master/src/map/modifier.h
... though admittedly it's unclear for some, and you'll need to search the repo for mod name to see how it's implemented.

To make a new modifier, you would take the next spare modifier, currently 842 (see line 655) and assign it a name.  You would add the same new modifier id/name to status.lua
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/status.lua, line 1361.

Next you would implement the new modifier - either in the core or, in the case of a simple JA duration modifier, in that ability's .lua script.  Similar to how flee duration is coded in the flee script.

Finally, you would find all the equipment that has this mod, and make sure it's entered into sql/item_mods.sql (for standard mods), sql/item_mods_pet.sql (for mods that affect your pet rather than you), and sql/item_latents.sql, for mods that are only triggered under specific latent conditions.

**Comment by Whitechaser** [comment]
Wao!

I'll work on it immediately!
