### ISSUE TITLE
Addition of Salvage & WOTG Branches

### ISSUE THREAD

**Issue by Cryptexx** [DarkstarProject/darkstar#4162]
This isn't an issue particular to any file, more of a request. I wanted to post here instead of the DSP forums because it pertains to the repository (didn't see a spot here for general discussion/suggestions though).

Could we create two new branches for Salvage and WOTG work? I know a few servers have worked on the content, and each has made its own progress. Doesn't make sense to upload systems that aren't fully working/implemented to master or stable, but considering several people have put in some work towards the content, it would be nice if they had a public space to collaborate, share ideas, and see what other people have figured out or still need to work on.

I don't believe it's a core focus of the project right now, but I know several players are interested in having this content. I think if developers had a central point to showcase their work, then more progress would be made toward having these two things fully implemented in the future.

Anyone else agree?

**Comment by zynjec** [comment]
There is nothing stopping them from submitting PR's with the content, I think they've just chosen to keep the code to themselves.

**Comment by takhlaq** [comment]
by `not a focus of the project` we typically refer to core members not focusing on it (to be honest we just work on whatever we feel like)
of course if people wish to work on that content they're free to pull request it after which we'll likely create a new branch for any additional changes we need before merging in to master

**Comment by teschnei** [comment]
There's no problem merging incomplete content into master as long as it's disabled or has no rewards

**Comment by Cryptexx** [comment]
Adding on to what Zynjec said, I think that's true in many cases. I see people using it as an advertising point mainly. 

Thank you all for the replies. I do see a lot of salvage material already scripted within master. If I may ask - what are some of the issues with it? Are there any zones that are working (somewhat) yet? Not sure if I've missed something over the pull history...I've never heard of anyone actually having a working salvage yet and the forum discussion is spotty - hard to get a good sense of where it's at.

**Comment by TeoTwawki** [comment]
First I wanna say I am not opposed into dividing content updates into their own branches for specific expansion, on the premise that they'd merge to master on significant usability milestones while regularly merging master's updates back to them However one must also consider this is a small team and that's extra overhead work (time spent futzing with edit conflicts for example) to keep track of.

>There is nothing stopping them from submitting PR's with the content, I think they've just chosen to keep the code to themselves.

This. I see servers all the time doing adverts like :
```
Fully functional Nyzul Isle~
```
```
Fully working Rune Fencer!
```
```
Fully working PUP
```
Tho to be fair their definition "working" is iffy most times or includes non retail things. But often the parts that are retail don't get shared back for months or years, if at all, while they lead the window shopping players to think they have an exclusive **retail** thing.

If its retail done correct (maintainable) and not a loot pinata its not rejected.

Another thing is people get told
```
This thingX should be thingY
```
And interpret that as
```
You suck and your code sucks and you should feel bad
```
And then they hate the project for actually reviewing their code instead of rubber stamping it and from then on will say they don't share because we'll just reject it anyway. Fact: nearly every item its not been rejected at all, they just abandoned their Pull Request after being asked to change a thing. Seriously anyone that wants to can go look through the closed without merge ones and see that we left them open for a long time waiting and they never came back.

/endRantyTeoNovel

**Comment by teschnei** [comment]
Salvage currently has all the core framework done (registering instances, support for floors, teleporters, the various debuffs you enter with and the items to cleanse them), and is mostly just missing mob placements and mob behaviour.

**Comment by Cryptexx** [comment]
> Salvage currently has all the core framework done (registering instances, support for floors, teleporters, the various debuffs you enter with and the items to cleanse them), and is mostly just missing mob placements and mob behaviour.

So pretty much the hard work is done, it's just a matter of the finer details inside the instance, is how I take that.

**Comment by teschnei** [comment]
I was going to say that, but certain monster AI may not be so simple
(qiqirn runners, for example)

On Oct 26, 2017 3:03 PM, "Cryptexx" <notifications@github.com> wrote:

Salvage currently has all the core framework done (registering instances,
support for floors, teleporters, the various debuffs you enter with and the
items to cleanse them), and is mostly just missing mob placements and mob
behaviour.

So pretty much the hard work is done, it's just a matter of the finer
details inside the instance, is how I take that.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DarkstarProject/darkstar/issues/4162#issuecomment-339800293>,
or mute the thread
