### ISSUE TITLE
Somnolence has damage calculation but doesn't subtract it from target

### ISSUE THREAD

**Issue by Whitechaser** [DarkstarProject/darkstar#4223]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_05

**_Server Version_** (type `!revision` in game) **:** Unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
I think [this](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/abilities/pets/somnolence.lua) is basically missing a:

`target:delHP(dmg);`
`target:updateEnmityFromDamage(pet,dmg);`

One thing I couldn't figure out though is why it says target "takes 0 points of damage" when I use it. I'm assuming the returned value is for the message? Other than that it won't be doing any damage at all.

**Comment by TeoTwawki** [comment]
neither of those would effect the message. the damage number is being returned here:
https://github.com/DarkstarProject/darkstar/blob/5078b8b1b71c30af4a5fbcb9075787e5a9a3cd3f/scripts/globals/abilities/pets/somnolence.lua#L35
so that variable `dmg` would have to be zero by that point (or nil, since nil would also get treated as zero). **There is probably a console log error on the server you play on.**
