### ISSUE TITLE
Server Vana Time is 5 ticks (seconds equivalent?) off Retail

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4247]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
I pressed both of the "Current Time" menu buttons (retail and dsp server) at the same time and got:

**Retail:** 
Vana'diel: 11/8/1288, Windsday, 3:20    Full Moon (93%)
Earth: Nov. 18, 2017 11:03:12am

**dsp:**   
Vana'diel 1288/11/18, Windsday, 3:25   Full Moon (93%)
Earth: Nov. 18, 2017 11:03:12

**Comment by teschnei** [comment]
My server is less than a vana'diel minute ahead of retail (about half a second).  This is easily explained by ping between Japan and where I am.  If you are experiencing a bigger delay, it is most likely because the machine you run your server on is has a clock that is farther ahead than the unix time of retail servers (or you have 5000 ping, but that's probably not the case).  You may want to check your time sync settings to ensure your system's time is correct.

**Comment by teschnei** [comment]
Alternatively, we could reimplement the time offset and you could set that to -5 or something around there and that would also work
