### ISSUE TITLE
Misc battlefields borked

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#4343]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
n/a

**_Server Version_** (type `!revision` in game) **:** 
90c6b9eafd04b1bcf4adddcd0c98555574893534

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Opened issue on behalf of legion after making sure they _DO NOT_ have custom crap causing it.

###### [As opposed to jumping to conclusions and then ticking me off while I try to help.](https://www.tenor.co/wGGh.gif)

**Comment by TeoTwawki** [comment]
Looks like some other assorted battlefield including avatar battles are afflicted by this nonsense too.

**Comment by TeoTwawki** [comment]
Players have discovered battlefields "Divine Punishers" and "Saintly Invitation" got mixed up somehow. They try to enter Saintly Invitation for the windurst mission they get the Divine Punishers BCNM showing on the entry menu instead.

**Comment by TeoTwawki** [comment]
Level capping sometimes not applying to all entrants either.

**Comment by takhlaq** [comment]
im not wanting to touch them on master, rather people jump in and help kj reimplement dynamis and temenos/limbus on bcnmcrap at this point

**Comment by TeoTwawki** [comment]
I started using this issue as a catch all "we already know" record

**Comment by TeoTwawki** [comment]
Another one:
![image](https://user-images.githubusercontent.com/6871475/35891378-e6d8ca28-0b71-11e8-84be-4f6a06dfa726.png)

None of those are what should have been displaying. Master is basically broken as far as BCNM go, until that BCNM branch gets merged. Please outline/checklist for people wtf needs to get done in that branch to reimplement the remaining parts of dynamis and temenos/limbus.
![default](https://user-images.githubusercontent.com/6871475/35891491-97e87b06-0b72-11e8-9b48-76a28c6e9376.jpg)

**Comment by teschnei** [comment]
Here's what's left on that branch:

- [ ] make sure the existing battlefields work (that includes limbus)
- [ ] QA the mob groups for dynamis - some of them don't spawn because of invalid groupid/poolid/etc (valkurm's flytraps, and I think almost all TEs)
- [ ] finish the proc system.  Mostly done, but I need a way to add an item to treasure pool that will take treasure hunter into account (so excludes the current method that we just for chests, etc), and a way to customize it for specific currency drops (or random ones, in the case of goblins/taurus)
- [ ] fix the item drop pools for all the dynamis monsters, if they are wrong.  Not sure on it, haven't looked.  Probably also includes the pop items for NMs
- [ ] script the pops for NMs (trading item to ???)
- [ ] scripting the bosses (qufim's status effects, beaucedine's teleporting, etc). Probably can skip this one to get this done faster, though

The rest is pretty minor (the timeout messages, for example) that can be fixed later
