### ISSUE TITLE
weather latent effects

### ISSUE THREAD

**Issue by dwn134** [DarkstarProject/darkstar#4771]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180203_1

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
put on rain hat id 15220, regen +1 with rain weather
set weather to rain = nothing
set weather to wind = regen +1
seems the param for weather is off on latent effects

**Comment by zynjec** [comment]
They work, just... GetWeatherElement returns a value different than whoever added rain hat expected, or it's changed since they added it.

https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/zoneutils.cpp#L1006
```
3,  //WEATHER_WIND
3,  //WEATHER_GALES
```
So right now, Rain Hat is adding its latent on element 3 (wind), when it should really be triggering on element 6 (water)
```
6,  //WEATHER_RAIN
6,  //WEATHER_SQUALL
```

**Comment by dwn134** [comment]
I'm looking at the file for latent and it shows the wrong order then  I'm
seeing water as 3

**Comment by zynjec** [comment]
The comment in `latent_effect.h` shows the incorrect values, for the purposes of weather-based latent, looks at the elemental value it's returning in https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/zoneutils.cpp#L1006

**Comment by dwn134** [comment]
Should I send in the correct values in a pull for the latent header for
less confusion?
