### ISSUE TITLE
Utsusemi wont overwrite on Zone in

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4986]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30180604_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When you zone with shadows already on, they cannot be overwritten.

1. Change Job to NIN
2. Cast Utsusemi: Ichi
3. Zone
4. Cast Utsusemi: Ni and get "no effect" message and no Ni shadows

Also will not let you overwrite same tier upon zone in. To get around this, you must manually remove the shadows before recasting and overwrites will go back to working as normal. (until next zone)

**Comment by teschnei** [comment]
I think shadows are stored as a Mod? That won't work for this case since
modifiers aren't saved on zoning.  However, I think they were implemented
as a mod because effects didn't have enough extra places to store things,
so maybe they can be moved back into the effect now.  I think any case
where we are dealing with the mod, we have to check the effect anyways..
