### ISSUE TITLE
Increased meal duration increases durration on zone

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5457]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181103_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
click sanction with increased meal duration but on a food and zone, it will increase in duration everytime you zone by double

**Comment by TeoTwawki** [comment]
paging @jmcmorris, can you check into this?

**Comment by jmcmorris** [comment]
@TeoTwawki yeah, that undoubtedly is caused by `dsp.mod.FOOD_DURATION` that I added. It likely needs to be applied up the callstack so that the mod isn't reapplied when zoning.

**Comment by TeoTwawki** [comment]
@jmcmorris ~~maybe, I didn't think it would be a problem during review because normally char is rebuilt on zone. The refresh/regen etc doesn't get stacked like that.~~ realized it while typing, and I should have caught it in review: its being applied in the effect container itself. Should likely be applied in the food effect handling directly. Does retail just mod durations of food being **used** while sanction is in effect, or modify food duration you already have on you? I always assumed the former.

**Comment by TeoTwawki** [comment]
clarification: its being done to an effect that already exists, in the status effect container
