### ISSUE TITLE
Distance check for NM failing, mobs aggroing players when loaded.

### ISSUE THREAD

**Issue by Snugglesffxi** [DarkstarProject/darkstar#5798]
Video of issue: https://clips.twitch.tv/DeliciousHonestKimchiPanicBasket

I believe it has to do with #5778 wren said CanDetectTarget at the bottom of the function is being skipped due to a return.

**Comment by wrenffxi** [comment]
I believe these lines aren't needed:
https://github.com/DarkstarProject/darkstar/blob/af73f7b883c4c302e65cdd67c1c4fda43c877da6/src/map/ai/controllers/mob_controller.cpp#L964-L967

Because the ALWAYS_AGGRO check to bypass level difference already happens here:
https://github.com/DarkstarProject/darkstar/blob/af73f7b883c4c302e65cdd67c1c4fda43c877da6/src/map/zone_entities.cpp#L460-L465

Unsure if #5778 was trying to use this mobmod to do more than bypass level difference.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/5785

**Comment by TeoTwawki** [comment]
I fixed and tested it but just has not been merged yet because I can't self merge

**Comment by TeoTwawki** [comment]
@wrenffxi the intent was to make it not only bypass lv but also bypass normal agro (passive mob can then agro using that mod) but it mistakenly took out sight/sound range checks too

**Comment by Snugglesffxi** [comment]
Thanks Wren and Teo <3 great work, will close this as soon as #5785 is merged.
