### ISSUE TITLE
My SC WS use seems a little high

### ISSUE THREAD

**Issue by helixhamin** [DarkstarProject/darkstar#6023]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190403_0

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by helixhamin** [comment]
![Capture](https://user-images.githubusercontent.com/2202779/58064613-13186500-7b40-11e9-8bd3-59132461abbb.PNG)

**Comment by helixhamin** [comment]
Just realized, the one with the rather large ws is the one with the shield.
Now she is hitting almost 25k damage...

**Comment by Delkathus** [comment]
Confirmed, it only seems to work with fast blade and similar but only with a shield equipped.
![image](https://user-images.githubusercontent.com/5308906/58110898-67622a00-7bbe-11e9-8518-9fe53ff0c286.png)

**Comment by teschnei** [comment]
It's because m_Weapons is an array of CItemWeapon, but sometimes we put non-weapons into it (shields, maybe others).  Then we don't make sure that they're actually weapons when we go use them for stuff, and the weapon-specific functions just end up reading whatever in memory.  I think we should change m_Weapons to be an array of CItemArmor (despite the name) and then make sure to check isType before doing any weapon-specific things on them.  I got started on it yesterday but I wouldn't be able to finish it until later.  It should be relatively easy for someone else to fix if they want to have a crack at it though: change the type in the charentity header, then try to compile and fix all the compiler errors (which will almost certainly be dynamic_casting the pointer and checking for null).

**Comment by Delkathus** [comment]
https://github.com/DarkstarProject/darkstar/blob/0fb80ca536bf22de28d3a86745d896cad3cbfb1d/scripts/globals/weaponskills.lua#L258

Seems to be the line causing a ruckus.
