### ISSUE TITLE
Option to Toggle On/Off Retro Dynamis

### ISSUE THREAD

**Issue by Delkathus** [DarkstarProject/darkstar#6175]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 20110829_E

**_Source Branch_** (master/stable) **:**  Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

With the re-work of Dynamis/Limbus and all instanced based and bcnm based events, it came to my attention that dynamis is forced to be Neo-Dynamis in lieu of Retro Dynamis now. For those servers who do not use any content above 75 era this is extremely inconvenient to those servers.

An option in the config to toggle retro/neo would be fantastic and will give more flexibility to all server era's. 

If it's already being worked on then close this, if not then here it be. <3

**Comment by zynjec** [comment]
We have no real interest in maintaining multiple versions of a system in the main project.

**Comment by ibm2431** [comment]
Servers that want "retro" Dynamis should put in work on Dynamis [D] and then just use monster level scaling :wink:

**Comment by TeoTwawki** [comment]
> We have no real interest in maintaining multiple versions of a system in the main project.

Its not a lack of interest. More accurately do not think our time will be well spent continuously maintaining such a colossal pain the in the neck that has been removed from retail when it is much easier for end users to modify Dynamis [D] on their own server into a facsimile of it than it is to create all the extra things needed to have it both ways here. A setting was on the table before DynaD happened. As it was a ton of mobs we were using were deleted from retail which is why they showed as "NPC".

DynaD doesn't work exactly like retro Dyna, but wouldn't be that bad to modify into it (and since we don't yet have it at all, would be easy to just roll your own Dynamis there)
