### ISSUE TITLE
Battlefield cleans up before cut scene finishes - THE CELESTIAL NEXUS

### ISSUE THREAD

**Issue by Doytoend** [DarkstarProject/darkstar#6318]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Encountered the issue during the final Zilart mission fight "THE_CELESTIAL_NEXUS". When entering the BCNM a cut scene plays and the battlefield ticks begin. Before the cut scene finishes the "Another event was called.." text appears in the chat log. When the cut scene finished the player is inside the BCNM but the Eald'narche and the other mobs have not spawned.

The issue seems to come from the battlefield.lua file. During the cut scene it cannot detect the mobs and ultimately set status to "WON" as the "killedallmobs" variable is initially set to true.

Then the following code is called and the battlefield is cleaned up
```lua
        if canLeave and cutsceneTimer >= 15 then
            battlefield:cleanup(true)
        end
```
I changed the 15 to a 100 and managed to get past the cut scene and spawn Eald'narche but once 100 ticks occurred I "WON" the fight and the end cut scene occurred and I was zoned back to Hall of Gods as expected.

**Comment by Doytoend** [comment]
Suggest changing killedallmobs to false and then change the for loop checking the mobs alive status
```
    for _, mob in pairs(mobs) do
        if mob:isAlive()  then
            killedallmobs = false
            break
        end
    end
```

**Comment by cocosolos** [comment]
This happens in a few fights where there's multiple phases to the fight and the target mob isn't spawned at the start. In this case, there are two Eldnarche mobs, one for each phase of the fight. His second form isn't spawned, and is considered "dead", until the first form is killed. Because only the second form is marked as the win condition, win conditions are triggered as soon as you enter. If both forms are set as required, win conditions are triggered after the first form before the second form spawns. #6299 should fix these issues

**Comment by Doytoend** [comment]
Thanks @cocosolos it is now working as expected after the merge. Both forms appeared and the battlefield did not exit prematurely.
