### ISSUE TITLE
Summoner Unlock Quest: I Can Hear a Rainbow

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#802]
Looks like folks aren't getting the CS triggers while on the SMN flag quest. We've tried about every zone and forcing weather and zoning players and still not registering.

**Comment by JoeCT** [comment]
I actually did some work on this quest about 2 years ago. I'll take a look and see what I can figure out.  I know it worked back then...

**Comment by JoeCT** [comment]
When entering a zone which is related to the quest, a function is called which determines whether or not the player has Carbuncle's Ruby and whether the player has accepted the I Can Hear a Rainbow quest.  The problem is that hasItem(), when called in function onZoneIn(), is returning false irregardless of whether the item is in inventory or not.

This is repeatable, add item 1125 to inventory and paste the following into the onZoneIn() function for any zone.

if( player:hasItem( 1125, 0)) then   -- Player has Carbuncle's Ruby?
printf("True");
else
printf("False");
end

Anyone have any ideas why this function is no longer working properly?

**Comment by JoeCT** [comment]
I took a look at charutils.cpp to see if I could determine a cause for this issue and in the LoadChar() function near the end you can see that the line "PChar->m_event.EventID = luautils::OnZoneIn(PChar);" is before the line "charutils::LoadInventory(PChar);" Placing the latter line before the former and recompiling solves this issue.

**Comment by teschnei** [comment]
unfortunately, it breaks some other stuff which is why I moved it there

**Comment by JoeCT** [comment]
I've been looking into using AfterZoneIn() to trigger this quest.  It's used in six zones to to send visual packets.  I placed a printf() inside of one to see when it triggered, but never got any output.  Anyone know what I'm doing wrong?

**Comment by korietsu** [comment]
Is it possible to use onGameHour to call the function check?

**Comment by JoeCT** [comment]
I have submitted a pull request (#811) to resolve this issue.

**Comment by teschnei** [comment]
inventory should be available in onZoneIn now
