### ISSUE TITLE
buffer length error,  getName returning null on zone

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#888]
https://www.dropbox.com/s/35z4e3jgjgbitk4/city%20crash%20zone%20getname%202-5-15.7z?dl=0

players have had it happen when using warp scrolls, outpost warps, seems to happen in cities more often than anywhere else. we have our server split into groups, and the city group goes down way more often; hourlong uptimes while combat zones get up to 20-30 hour uptimes.  combat zones may only be immune because I have disabled the summoner quest.

**Comment by Scavenge** [comment]
with the warp scrolls, i tried to have the same player that appeared in the autos of a crash replicate the process. he had said he logged in and immediately used a warp scroll, and then it crashed and when server came back up he was still in the combat zone but had lost his scroll.  i had him take another scroll and go back and use it again, but this time no issue. the only difference i see is that he logged in and immediately used the scroll, possibly before he had finished loading in.

**Comment by teschnei** [comment]
The server is done loading the char when his screen fades in, and inventory
is last among the process anyways. At any rate, it's because of a char
loading into a zone that the server doesn't handle. In this example, it was
the city that crashed right? (Where his home point was), and not the zone
he used the scroll in?

**Comment by Scavenge** [comment]
yes correct, but it made him crash as well.

**Comment by Scavenge** [comment]
as a precaution we are updating our home point crystal luas to the recent commit, at first glance we worried it might be that he had one of those as his home point

**Comment by teschnei** [comment]
Its more likely an issue with something in the core or the warp script
itself. General outline like this: use warp, server sends packet to client
with IP and port of city server. Database is updated with new pos/zone (at
home point). So far is normal. Then, something else saves pos/zone again,
except this time the pos/zone are where the player is. When he loads in to
city server, server sees he's in zone that is not handled (the one he came
from) and then crashes so that you'll email me!  I'd wager maybe the
incoming pos packets, but I've got no internet yet in my apartment to check

**Comment by Scavenge** [comment]
i have a hunch that other crashes we are getting are also related to this, some are sql, most are charutils, but all of them reference back to charutils::LoadChar at some point in the callstack, and so far as I can tell they are consistently showing a character's destination and prevzone to be on seperate servers.  they all also have a status of STATUS_DISAPPEAR (which i assume is just from zoning).  i know you're still moving but just wanted to update with plenty of info beacuse It doesn't seem like it's related to home points or the warp script anymore since a few of them are from players moving between normal combat zones and HNM zones.

**Comment by xdemolish** [comment]
only way i've been able to reproduce 99% of the time is by sticking a debug break on CZone::DecreaseZoneCounter
seems to be caused by a delay between client and server, possibly due to the client resending packets until it gets a response?

**Comment by teschnei** [comment]
If it can be reliably reproduced, it can be fixed. I'll look when I get
home. Were you using two servers and zoning between them?

**Comment by xdemolish** [comment]
ya, one server with all but cape teriggan loaded, and the other with just cape teriggan
both on same ip but different port, crash occurred both ways when the breakpoint was hit on CZone::DecreaseZoneCounter
think it was anything > 1 sec delay that caused it

**Comment by teschnei** [comment]
perfect, thanks demo

**Comment by teschnei** [comment]
993ab35cea393d3e585a1ea517dccc9ba1e3e169
