### ISSUE TITLE
Mobs: Burrowed Antlions are untargetable and don't ambush.

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#904]
Zone: Attowah Chasm
Mobs: Lioumere (NM for CoP)
           Pit_Antlion
           Cave_Antlion
           Burrow_Antlion

I saw the Pit_Ambush ability wasn't tied to a mob family and assume that is why they don't ambush, but they are untargetable when they come out of the ground. You can scan for them or let them attack you in order to target, but selecting them doesn't seem to work.

I have tried the following in the lua for the NM Lioumere with no success:

function OnMobSpawn(mob)
	mob:untargetable(0);
end;

I am not sure if the mob lua is handled on the fly like items/abilities/doors/etc.or on start up only.

**Comment by TeoTwawki** [comment]
I just checked and Ambusher Antlion popped up for me just fine once I dropped GM flag and tapped resting key (My lv too high for him to agro me without resting). The NM for the CoP mission should pop up and attack because of the script on his pop point. I just did that mission a few weeks ago, so if it broke its very recent.

**Comment by nesstea** [comment]
I have a fix. Will be committing soon.

**Comment by nesstea** [comment]
@xdemolish can we reopen this? my fix didn't work.

**Comment by teschnei** [comment]
Isn't that what your testing was for? You did test, right?

**Comment by nesstea** [comment]
Yes, but I was told I did the wrong thing and was told to add mobmods to the pool in the db. It didn't work.
